package com.qimeng.bs.admin.inte.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.qimeng.common.Page;
import com.qimeng.bs.admin.inte.bean.SystemInterface;

@Repository
public interface SystemInterfaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_interface
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    int deleteByPrimaryKey(Integer interfaceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_interface
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    int insert(SystemInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_interface
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    int insertSelective(SystemInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_interface
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    SystemInterface selectByPrimaryKey(Integer interfaceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_interface
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    int updateByPrimaryKeySelective(SystemInterface record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_interface
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    int updateByPrimaryKey(SystemInterface record);

	@SuppressWarnings("unchecked")
	List<SystemInterface> searchAllByPage(Page page);
	
	SystemInterface selectByInterfaceCode(String interfaceCode);
}