package com.qimeng.bs.market.news.bean;

import org.directwebremoting.annotations.DataTransferObject;

import java.util.Date;

@DataTransferObject
public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_id
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    private Integer newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_title
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    private String newsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.kind
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.publisher
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.publish_time
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_id
     *
     * @return the value of news.news_id
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_id
     *
     * @param newsId the value for news.news_id
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_title
     *
     * @return the value of news.news_title
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_title
     *
     * @param newsTitle the value for news.news_title
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.kind
     *
     * @return the value of news.kind
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.kind
     *
     * @param kind the value for news.kind
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    public void setKind(String kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.publisher
     *
     * @return the value of news.publisher
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.publisher
     *
     * @param publisher the value for news.publisher
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.publish_time
     *
     * @return the value of news.publish_time
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.publish_time
     *
     * @param publishTime the value for news.publish_time
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbggenerated Sat Mar 15 16:47:34 CST 2014
     */
    public void setContent(String content) {
        this.content = content;
    }
}