package com.qimeng.bs.market.user.dao;

import com.qimeng.bs.market.user.bean.DmAddress;
import com.qimeng.common.Page;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface DmAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_address
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_address
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    int insert(DmAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_address
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    int insertSelective(DmAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_address
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    DmAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_address
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    int updateByPrimaryKeySelective(DmAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_address
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    int updateByPrimaryKey(DmAddress record);

    List<DmAddress> selectByMerchantId(Page page);

    void changeDefaultAddress(Map params);

    void setDefaultAddress(Map params);

    DmAddress selectFirstAddess(Integer merchantId);

    List<DmAddress> selectAllByMerchantId(Integer merchantId);
}