package com.qimeng.bs.market.user.dao;

import com.qimeng.bs.market.user.bean.ReferrerInfo;
import com.qimeng.common.Page;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ReferrerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referrer_info
     *
     * @mbggenerated Sat Jan 25 16:42:41 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referrer_info
     *
     * @mbggenerated Sat Jan 25 16:42:41 CST 2014
     */
    int insert(ReferrerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referrer_info
     *
     * @mbggenerated Sat Jan 25 16:42:41 CST 2014
     */
    int insertSelective(ReferrerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referrer_info
     *
     * @mbggenerated Sat Jan 25 16:42:41 CST 2014
     */
    ReferrerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referrer_info
     *
     * @mbggenerated Sat Jan 25 16:42:41 CST 2014
     */
    int updateByPrimaryKeySelective(ReferrerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table referrer_info
     *
     * @mbggenerated Sat Jan 25 16:42:41 CST 2014
     */
    int updateByPrimaryKey(ReferrerInfo record);

    List<ReferrerInfo> findPresentee(Integer referrerId);

    List<ReferrerInfo> queryMyReferrers(Page page);

    List<ReferrerInfo> getNextLevel(Integer userId);

    ReferrerInfo queryUpLevel(Integer userId);
}