package com.qimeng.bs.system.staticdata.bean;

public class SensitiveWord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.ID
     *
     * @mbggenerated Fri Dec 06 11:08:46 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.WORD
     *
     * @mbggenerated Fri Dec 06 11:08:46 CST 2013
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.PINYIN
     *
     * @mbggenerated Fri Dec 06 11:08:46 CST 2013
     */
    private String pinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.ID
     *
     * @return the value of sensitive_word.ID
     *
     * @mbggenerated Fri Dec 06 11:08:46 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.ID
     *
     * @param id the value for sensitive_word.ID
     *
     * @mbggenerated Fri Dec 06 11:08:46 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.WORD
     *
     * @return the value of sensitive_word.WORD
     *
     * @mbggenerated Fri Dec 06 11:08:46 CST 2013
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.WORD
     *
     * @param word the value for sensitive_word.WORD
     *
     * @mbggenerated Fri Dec 06 11:08:46 CST 2013
     */
    public void setWord(String word) {
        this.word = word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.PINYIN
     *
     * @return the value of sensitive_word.PINYIN
     *
     * @mbggenerated Fri Dec 06 11:08:46 CST 2013
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.PINYIN
     *
     * @param pinyin the value for sensitive_word.PINYIN
     *
     * @mbggenerated Fri Dec 06 11:08:46 CST 2013
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }
}