package com.qimeng.bs.admin.goods.dao;

import java.util.List;

import com.qimeng.common.Page;
import com.qimeng.bs.admin.goods.bean.DmAdvertisement;

public interface DmAdvertisementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_advertisement
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_advertisement
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    int insert(DmAdvertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_advertisement
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    int insertSelective(DmAdvertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_advertisement
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    DmAdvertisement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_advertisement
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    int updateByPrimaryKeySelective(DmAdvertisement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_advertisement
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    int updateByPrimaryKey(DmAdvertisement record);
    
    List<DmAdvertisement> findAdvertisement(Object params);
    List<DmAdvertisement>  findAllAdvertisement(Page<DmAdvertisement> page);
}