package com.qimeng.bs.admin.goods.dao;

import com.qimeng.bs.admin.goods.bean.DmGoodsPlan;
import org.springframework.stereotype.Repository;

@Repository
public interface DmGoodsPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_plan
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    int deleteByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_plan
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    int insert(DmGoodsPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_plan
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    int insertSelective(DmGoodsPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_plan
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    DmGoodsPlan selectByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_plan
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    int updateByPrimaryKeySelective(DmGoodsPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_plan
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    int updateByPrimaryKey(DmGoodsPlan record);

    DmGoodsPlan selectActiveGoodsPlan(String goodsId);
}