package com.qimeng.bs.admin.goods.dao;

import org.springframework.stereotype.Repository;

import com.qimeng.bs.admin.goods.bean.DmGoods;
import com.qimeng.bs.admin.goods.bean.DmGoodsTagValue;
@Repository
public interface DmGoodsTagValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_tag_value
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    int deleteByPrimaryKey(Integer tagValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_tag_value
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    int insert(DmGoodsTagValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_tag_value
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    int insertSelective(DmGoodsTagValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_tag_value
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    DmGoodsTagValue selectByPrimaryKey(Integer tagValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_tag_value
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    int updateByPrimaryKeySelective(DmGoodsTagValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_tag_value
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    int updateByPrimaryKey(DmGoodsTagValue record);
    
    void attachGoodTagsItems(DmGoods record);
    
    void releaseAllTagsItems(Integer tagGroupId);
    
    void deleteAllTagsItemsByItemId(Integer itemId);
    
    
}