package com.qimeng.bs.admin.goods.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.qimeng.common.Page;
import com.qimeng.bs.admin.goods.bean.DmGoods;

@Repository
public interface DmGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods
     *
     * @mbggenerated Mon Dec 16 14:14:23 CST 2013
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods
     *
     * @mbggenerated Mon Dec 16 14:14:23 CST 2013
     */
    int insert(DmGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods
     *
     * @mbggenerated Mon Dec 16 14:14:23 CST 2013
     */
    int insertSelective(DmGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods
     *
     * @mbggenerated Mon Dec 16 14:14:23 CST 2013
     */
    DmGoods selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods
     *
     * @mbggenerated Mon Dec 16 14:14:23 CST 2013
     */
    int updateByPrimaryKeySelective(DmGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods
     *
     * @mbggenerated Mon Dec 16 14:14:23 CST 2013
     */
    int updateByPrimaryKey(DmGoods record);
    
    List<DmGoods> findGoods(Object params);

    void unattachCatalog(Integer catalogId);

    List<DmGoods> findAllGoods(Page<DmGoods> page);

//    List<DmGoods> findGoodsByPackageId(Integer packageId);
}