package com.qimeng.bs.admin.goods.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.qimeng.common.Page;
import com.qimeng.bs.admin.goods.bean.DmGoodsTag;
import com.qimeng.bs.admin.goods.bean.DmTags;
@Repository
public interface DmGoodsTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_tag
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    int deleteByPrimaryKey(Integer tagGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_tag
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    int insert(DmGoodsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_tag
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    int insertSelective(DmGoodsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_tag
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    DmGoodsTag selectByPrimaryKey(Integer tagGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_tag
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    int updateByPrimaryKeySelective(DmGoodsTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_tag
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    int updateByPrimaryKey(DmGoodsTag record);
    
    List<DmTags> findAllTags(Page<DmTags> page);
    
    List<DmGoodsTag> findGoodsTagByTagId(Integer tagId);
    
    List<DmGoodsTag> findGoodsTagByGoodId(Integer goodsId);
    
    void deleteByGoodId(Integer goodId);
    void deleteByTagId(Integer tagId);
}