package com.qimeng.bs.admin.goods.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.qimeng.common.Page;
import com.qimeng.bs.admin.goods.bean.DmGoodsPackage;
@Repository
public interface DmGoodsPackageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_package
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    int deleteByPrimaryKey(Integer packageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_package
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    int insert(DmGoodsPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_package
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    int insertSelective(DmGoodsPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_package
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    DmGoodsPackage selectByPrimaryKey(Integer packageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_package
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    int updateByPrimaryKeySelective(DmGoodsPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_package
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    int updateByPrimaryKey(DmGoodsPackage record);
    
    List<DmGoodsPackage> findAllGoodPackages(Page<DmGoodsPackage> page);
    
    List<DmGoodsPackage> findGoodPackages(Object  param);
    
    void  attachGoods(DmGoodsPackage record);
    void unattachGoodsByPackageId(Integer packageId);
    
    void unattachGood(@Param("packageId")Integer packageId,@Param("goodsId")Integer goodsId);
}