package com.qimeng.bs.admin.goods.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.qimeng.common.Page;
import com.qimeng.bs.admin.goods.bean.DmTags;
@Repository
public interface DmTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_tags
     *
     * @mbggenerated Thu Dec 12 10:16:19 CST 2013
     */
    int deleteByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_tags
     *
     * @mbggenerated Thu Dec 12 10:16:19 CST 2013
     */
    int insert(DmTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_tags
     *
     * @mbggenerated Thu Dec 12 10:16:19 CST 2013
     */
    int insertSelective(DmTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_tags
     *
     * @mbggenerated Thu Dec 12 10:16:19 CST 2013
     */
    DmTags selectByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_tags
     *
     * @mbggenerated Thu Dec 12 10:16:19 CST 2013
     */
    int updateByPrimaryKeySelective(DmTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_tags
     *
     * @mbggenerated Thu Dec 12 10:16:19 CST 2013
     */
    int updateByPrimaryKey(DmTags record);
    
    List<DmTags> findTags(Object params);
    
    List<DmTags> findAllTags(Page<DmTags> page);
}