package com.qimeng.bs.admin.goods.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import com.qimeng.common.Page;
import com.qimeng.bs.admin.goods.bean.DmTagsItem;
@Repository
public interface DmTagsItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_tags_item
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_tags_item
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    int insert(DmTagsItem record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_tags_item
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    int insertSelective(DmTagsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_tags_item
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    DmTagsItem selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_tags_item
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    int updateByPrimaryKeySelective(DmTagsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_tags_item
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    int updateByPrimaryKey(DmTagsItem record);
    
    List<DmTagsItem> findAllTagsItems(Page<DmTagsItem> page);
    List<DmTagsItem> findTagsItems(Object params);
    List<DmTagsItem> selectTagsItems(Integer tagId);
    List<Map> findGoodsTag(Object params);
    
    void unattachTag(Integer tagId);
}