package com.qimeng.bs.market.activity.bean;

import org.directwebremoting.annotations.DataTransferObject;

import java.util.Date;
@DataTransferObject
public class DmExecuteList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_execute_list.ID
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_execute_list.ACT_ID
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private Integer actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_execute_list.PHONE_NO
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_execute_list.CREATE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_execute_list.STATE
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_execute_list.DEAL_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private Date dealTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_execute_list.ID
     *
     * @return the value of dm_execute_list.ID
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_execute_list.ID
     *
     * @param id the value for dm_execute_list.ID
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_execute_list.ACT_ID
     *
     * @return the value of dm_execute_list.ACT_ID
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public Integer getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_execute_list.ACT_ID
     *
     * @param actId the value for dm_execute_list.ACT_ID
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setActId(Integer actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_execute_list.PHONE_NO
     *
     * @return the value of dm_execute_list.PHONE_NO
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_execute_list.PHONE_NO
     *
     * @param phoneNo the value for dm_execute_list.PHONE_NO
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_execute_list.CREATE_TIME
     *
     * @return the value of dm_execute_list.CREATE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_execute_list.CREATE_TIME
     *
     * @param createTime the value for dm_execute_list.CREATE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_execute_list.STATE
     *
     * @return the value of dm_execute_list.STATE
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_execute_list.STATE
     *
     * @param state the value for dm_execute_list.STATE
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_execute_list.DEAL_TIME
     *
     * @return the value of dm_execute_list.DEAL_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_execute_list.DEAL_TIME
     *
     * @param dealTime the value for dm_execute_list.DEAL_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }
}