package com.qimeng.bs.market.activity.bean;

import org.directwebremoting.annotations.DataTransferObject;

import java.util.Date;

@DataTransferObject
public class DmMerchantActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.ACT_ID
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private Integer actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.GOODS_INST_ID
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private Integer goodsInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.MERCHANT_ID
     *
     * @mbggenerated Thu Dec 05 10:40:08 CST 2013
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.ACT_NAME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private String actName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.SEND_METHOD
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private String sendMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.SMS_CONTENT
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private String smsContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.BEGIN_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.END_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.PRODUCE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private Date produceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.RULE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private String ruleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.CREATE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.STATE
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_activity.STATE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    private Date stateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.ACT_ID
     *
     * @return the value of dm_merchant_activity.ACT_ID
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public Integer getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.ACT_ID
     *
     * @param actId the value for dm_merchant_activity.ACT_ID
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setActId(Integer actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.GOODS_INST_ID
     *
     * @return the value of dm_merchant_activity.GOODS_INST_ID
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public Integer getGoodsInstId() {
        return goodsInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.GOODS_INST_ID
     *
     * @param goodsInstId the value for dm_merchant_activity.GOODS_INST_ID
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setGoodsInstId(Integer goodsInstId) {
        this.goodsInstId = goodsInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.MERCHANT_ID
     *
     * @return the value of dm_merchant_activity.MERCHANT_ID
     *
     * @mbggenerated Thu Dec 05 10:40:08 CST 2013
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.MERCHANT_ID
     *
     * @param merchantId the value for dm_merchant_activity.MERCHANT_ID
     *
     * @mbggenerated Thu Dec 05 10:40:08 CST 2013
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.ACT_NAME
     *
     * @return the value of dm_merchant_activity.ACT_NAME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public String getActName() {
        return actName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.ACT_NAME
     *
     * @param actName the value for dm_merchant_activity.ACT_NAME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setActName(String actName) {
        this.actName = actName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.SEND_METHOD
     *
     * @return the value of dm_merchant_activity.SEND_METHOD
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public String getSendMethod() {
        return sendMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.SEND_METHOD
     *
     * @param sendMethod the value for dm_merchant_activity.SEND_METHOD
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setSendMethod(String sendMethod) {
        this.sendMethod = sendMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.SMS_CONTENT
     *
     * @return the value of dm_merchant_activity.SMS_CONTENT
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public String getSmsContent() {
        return smsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.SMS_CONTENT
     *
     * @param smsContent the value for dm_merchant_activity.SMS_CONTENT
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setSmsContent(String smsContent) {
        this.smsContent = smsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.BEGIN_TIME
     *
     * @return the value of dm_merchant_activity.BEGIN_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.BEGIN_TIME
     *
     * @param beginTime the value for dm_merchant_activity.BEGIN_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.END_TIME
     *
     * @return the value of dm_merchant_activity.END_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.END_TIME
     *
     * @param endTime the value for dm_merchant_activity.END_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.PRODUCE_TIME
     *
     * @return the value of dm_merchant_activity.PRODUCE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public Date getProduceTime() {
        return produceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.PRODUCE_TIME
     *
     * @param produceTime the value for dm_merchant_activity.PRODUCE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setProduceTime(Date produceTime) {
        this.produceTime = produceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.RULE_TIME
     *
     * @return the value of dm_merchant_activity.RULE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public String getRuleTime() {
        return ruleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.RULE_TIME
     *
     * @param ruleTime the value for dm_merchant_activity.RULE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setRuleTime(String ruleTime) {
        this.ruleTime = ruleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.CREATE_TIME
     *
     * @return the value of dm_merchant_activity.CREATE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.CREATE_TIME
     *
     * @param createTime the value for dm_merchant_activity.CREATE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.STATE
     *
     * @return the value of dm_merchant_activity.STATE
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.STATE
     *
     * @param state the value for dm_merchant_activity.STATE
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_activity.STATE_TIME
     *
     * @return the value of dm_merchant_activity.STATE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public Date getStateTime() {
        return stateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_activity.STATE_TIME
     *
     * @param stateTime the value for dm_merchant_activity.STATE_TIME
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    public void setStateTime(Date stateTime) {
        this.stateTime = stateTime;
    }


    private String goodsName;

    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }
}