package com.qimeng.bs.market.activity.dao;

import com.qimeng.bs.market.activity.bean.DmExecuteList;
import com.qimeng.bs.market.activity.bean.DmMerchantActivity;
import org.springframework.stereotype.Repository;

@Repository
public interface DmExecuteListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_execute_list
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_execute_list
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    int insert(DmExecuteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_execute_list
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    int insertSelective(DmExecuteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_execute_list
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    DmExecuteList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_execute_list
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    int updateByPrimaryKeySelective(DmExecuteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_execute_list
     *
     * @mbggenerated Tue Dec 03 10:32:45 CST 2013
     */
    int updateByPrimaryKey(DmExecuteList record);

    void copyInstDataToExecuteList(DmMerchantActivity activity);

}