package com.qimeng.bs.market.comments.dao;

import com.qimeng.bs.market.comments.bean.DmGoodsEvaluation;
import org.springframework.stereotype.Repository;

@Repository
public interface DmGoodsEvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_evaluation
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    int deleteByPrimaryKey(Integer evaluationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_evaluation
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    int insert(DmGoodsEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_evaluation
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    int insertSelective(DmGoodsEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_evaluation
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    DmGoodsEvaluation selectByPrimaryKey(Integer evaluationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_evaluation
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    int updateByPrimaryKeySelective(DmGoodsEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_evaluation
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    int updateByPrimaryKey(DmGoodsEvaluation record);

    DmGoodsEvaluation queryEvaluationByGoodsId(int goodsId);

}