package com.qimeng.bs.admin.merchant.dao;

import java.util.List;
import java.util.Map;

import com.qimeng.bs.admin.merchant.bean.DmMerchant;

import org.springframework.stereotype.Repository;

@Repository
public interface DmMerchantMapper {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_merchant
     *
     * @mbggenerated Thu Dec 05 14:49:50 CST 2013
     */
    int deleteByPrimaryKey(Integer merchantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_merchant
     *
     * @mbggenerated Thu Dec 05 14:49:50 CST 2013
     */
    int insert(DmMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_merchant
     *
     * @mbggenerated Thu Dec 05 14:49:50 CST 2013
     */
    int insertSelective(DmMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_merchant
     *
     * @mbggenerated Thu Dec 05 14:49:50 CST 2013
     */
    DmMerchant selectByPrimaryKey(Integer merchantId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_merchant
     *
     * @mbggenerated Thu Dec 05 14:49:50 CST 2013
     */
    int updateByPrimaryKeySelective(DmMerchant record);
    
    int updateStateByPrimaryKey(DmMerchant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_merchant
     *
     * @mbggenerated Thu Dec 05 14:49:50 CST 2013
     */
    int updateByPrimaryKey(DmMerchant record);
    
    List<DmMerchant> findAllMerchant(Map param);

    DmMerchant findMerchantByUserId(Integer userId);
}