package com.qimeng.bs.admin.merchant.dao;

import java.util.List;
import java.util.Map;

import com.qimeng.common.Page;
import com.qimeng.bs.admin.merchant.bean.DmMerchantFile;
import org.springframework.stereotype.Repository;

@Repository
public interface DmMerchantFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_merchant_file
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_merchant_file
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    int insert(DmMerchantFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_merchant_file
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    int insertSelective(DmMerchantFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_merchant_file
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    DmMerchantFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_merchant_file
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    int updateByPrimaryKeySelective(DmMerchantFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_merchant_file
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    int updateByPrimaryKey(DmMerchantFile record);
    
    List<DmMerchantFile> findAllMerchantFile(Page page);
    
    List<DmMerchantFile> searchMerchantFiles(Map params);
}