package com.qimeng.bs.market.user.bean;

import org.directwebremoting.annotations.DataTransferObject;

import javax.ws.rs.FormParam;

@DataTransferObject
public class DmAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_address.ID
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_address.MERCHANT_ID
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_address.CONTACT_PERSON
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    @FormParam("contactPerson")
    private String contactPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_address.MOBILE_PHONE
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    @FormParam("mobilePhone")
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_address.PROVINCE
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    @FormParam("province")
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_address.CITY
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    @FormParam("city")
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_address.DISTRICT
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    @FormParam("district")
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_address.ADDRESS
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    @FormParam("address")
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_address.ZIP_CODE
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    @FormParam("zipCode")
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_address.IS_DEFAULT
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    @FormParam("isDefault")
    private String isDefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_address.ID
     *
     * @return the value of dm_address.ID
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_address.ID
     *
     * @param id the value for dm_address.ID
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_address.MERCHANT_ID
     *
     * @return the value of dm_address.MERCHANT_ID
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_address.MERCHANT_ID
     *
     * @param merchantId the value for dm_address.MERCHANT_ID
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_address.CONTACT_PERSON
     *
     * @return the value of dm_address.CONTACT_PERSON
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_address.CONTACT_PERSON
     *
     * @param contactPerson the value for dm_address.CONTACT_PERSON
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_address.MOBILE_PHONE
     *
     * @return the value of dm_address.MOBILE_PHONE
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_address.MOBILE_PHONE
     *
     * @param mobilePhone the value for dm_address.MOBILE_PHONE
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_address.PROVINCE
     *
     * @return the value of dm_address.PROVINCE
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_address.PROVINCE
     *
     * @param province the value for dm_address.PROVINCE
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_address.CITY
     *
     * @return the value of dm_address.CITY
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_address.CITY
     *
     * @param city the value for dm_address.CITY
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_address.DISTRICT
     *
     * @return the value of dm_address.DISTRICT
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_address.DISTRICT
     *
     * @param district the value for dm_address.DISTRICT
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_address.ADDRESS
     *
     * @return the value of dm_address.ADDRESS
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_address.ADDRESS
     *
     * @param address the value for dm_address.ADDRESS
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_address.ZIP_CODE
     *
     * @return the value of dm_address.ZIP_CODE
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_address.ZIP_CODE
     *
     * @param zipCode the value for dm_address.ZIP_CODE
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_address.IS_DEFAULT
     *
     * @return the value of dm_address.IS_DEFAULT
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_address.IS_DEFAULT
     *
     * @param isDefault the value for dm_address.IS_DEFAULT
     *
     * @mbggenerated Sun Jan 12 15:42:38 CST 2014
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault;
    }
}