package com.qimeng.bs.market.user.bean;

import org.directwebremoting.annotations.DataTransferObject;

import java.util.Date;
@DataTransferObject
public class ReferrerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referrer_info.id
     *
     * @mbggenerated Sat Jan 25 17:18:12 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referrer_info.referrer_id
     *
     * @mbggenerated Sat Jan 25 17:18:12 CST 2014
     */
    private Integer referrerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referrer_info.presentee_id
     *
     * @mbggenerated Sat Jan 25 17:18:12 CST 2014
     */
    private Integer presenteeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column referrer_info.create_time
     *
     * @mbggenerated Sat Jan 25 17:18:12 CST 2014
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referrer_info.id
     *
     * @return the value of referrer_info.id
     *
     * @mbggenerated Sat Jan 25 17:18:12 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referrer_info.id
     *
     * @param id the value for referrer_info.id
     *
     * @mbggenerated Sat Jan 25 17:18:12 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referrer_info.referrer_id
     *
     * @return the value of referrer_info.referrer_id
     *
     * @mbggenerated Sat Jan 25 17:18:12 CST 2014
     */
    public Integer getReferrerId() {
        return referrerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referrer_info.referrer_id
     *
     * @param referrerId the value for referrer_info.referrer_id
     *
     * @mbggenerated Sat Jan 25 17:18:12 CST 2014
     */
    public void setReferrerId(Integer referrerId) {
        this.referrerId = referrerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referrer_info.presentee_id
     *
     * @return the value of referrer_info.presentee_id
     *
     * @mbggenerated Sat Jan 25 17:18:12 CST 2014
     */
    public Integer getPresenteeId() {
        return presenteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referrer_info.presentee_id
     *
     * @param presenteeId the value for referrer_info.presentee_id
     *
     * @mbggenerated Sat Jan 25 17:18:12 CST 2014
     */
    public void setPresenteeId(Integer presenteeId) {
        this.presenteeId = presenteeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column referrer_info.create_time
     *
     * @return the value of referrer_info.create_time
     *
     * @mbggenerated Sat Jan 25 17:18:12 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column referrer_info.create_time
     *
     * @param createTime the value for referrer_info.create_time
     *
     * @mbggenerated Sat Jan 25 17:18:12 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    private String presenteeName;

    public String getPresenteeName() {
        return presenteeName;
    }

    public void setPresenteeName(String presenteeName) {
        this.presenteeName = presenteeName;
    }
}