package com.qimeng.bs.market.comments.bean;

import org.directwebremoting.annotations.DataTransferObject;

import java.util.Date;
@DataTransferObject
public class DmCustComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_comment.COMMENT_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_comment.GOODS_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_comment.MERCHANT_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_comment.ORD_DETAIL_NO
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private Integer ordDetailNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_comment.SCORE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_comment.ADVANTAGE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private String advantage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_comment.DISADVANTAGE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private String disadvantage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_comment.CUST_COMMENT
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private String custComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_comment.CREATE_TIME
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_comment.STATE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_comment.COMMENT_ID
     *
     * @return the value of dm_cust_comment.COMMENT_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_comment.COMMENT_ID
     *
     * @param commentId the value for dm_cust_comment.COMMENT_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_comment.GOODS_ID
     *
     * @return the value of dm_cust_comment.GOODS_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_comment.GOODS_ID
     *
     * @param goodsId the value for dm_cust_comment.GOODS_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_comment.MERCHANT_ID
     *
     * @return the value of dm_cust_comment.MERCHANT_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_comment.MERCHANT_ID
     *
     * @param merchantId the value for dm_cust_comment.MERCHANT_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_comment.ORD_DETAIL_NO
     *
     * @return the value of dm_cust_comment.ORD_DETAIL_NO
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public Integer getOrdDetailNo() {
        return ordDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_comment.ORD_DETAIL_NO
     *
     * @param ordDetailNo the value for dm_cust_comment.ORD_DETAIL_NO
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setOrdDetailNo(Integer ordDetailNo) {
        this.ordDetailNo = ordDetailNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_comment.SCORE
     *
     * @return the value of dm_cust_comment.SCORE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_comment.SCORE
     *
     * @param score the value for dm_cust_comment.SCORE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_comment.ADVANTAGE
     *
     * @return the value of dm_cust_comment.ADVANTAGE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public String getAdvantage() {
        return advantage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_comment.ADVANTAGE
     *
     * @param advantage the value for dm_cust_comment.ADVANTAGE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setAdvantage(String advantage) {
        this.advantage = advantage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_comment.DISADVANTAGE
     *
     * @return the value of dm_cust_comment.DISADVANTAGE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public String getDisadvantage() {
        return disadvantage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_comment.DISADVANTAGE
     *
     * @param disadvantage the value for dm_cust_comment.DISADVANTAGE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setDisadvantage(String disadvantage) {
        this.disadvantage = disadvantage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_comment.CUST_COMMENT
     *
     * @return the value of dm_cust_comment.CUST_COMMENT
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public String getCustComment() {
        return custComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_comment.CUST_COMMENT
     *
     * @param custComment the value for dm_cust_comment.CUST_COMMENT
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setCustComment(String custComment) {
        this.custComment = custComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_comment.CREATE_TIME
     *
     * @return the value of dm_cust_comment.CREATE_TIME
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_comment.CREATE_TIME
     *
     * @param createTime the value for dm_cust_comment.CREATE_TIME
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_comment.STATE
     *
     * @return the value of dm_cust_comment.STATE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_comment.STATE
     *
     * @param state the value for dm_cust_comment.STATE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setState(String state) {
        this.state = state;
    }

    private String merchantName;
    private String userName;
    private String headImage;


    public String getMerchantName() {
        return merchantName;
    }

    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getHeadImage() {
        return headImage;
    }

    public void setHeadImage(String headImage) {
        this.headImage = headImage;
    }
}