package com.qimeng.bs.market.comments.bean;

import org.directwebremoting.annotations.DataTransferObject;

@DataTransferObject
public class DmGoodsEvaluation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_evaluation.EVALUATION_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private Integer evaluationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_evaluation.GOODS_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_evaluation.TOTAL
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private Integer totalCount =0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_evaluation.AVG_SCORE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private Integer avgScore =0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_evaluation.LIKE_COUNT
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private Integer likeCount =0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_evaluation.FAVOURITE_COUNT
     *
     * @mbggenerated Mon Dec 16 11:00:06 CST 2013
     */
    private Integer favouriteCount =0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_evaluation.DISLIKE_COUNT
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    private Integer dislikeCount =0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_evaluation.EVALUATION_ID
     *
     * @return the value of dm_goods_evaluation.EVALUATION_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public Integer getEvaluationId() {
        return evaluationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_evaluation.EVALUATION_ID
     *
     * @param evaluationId the value for dm_goods_evaluation.EVALUATION_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setEvaluationId(Integer evaluationId) {
        this.evaluationId = evaluationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_evaluation.GOODS_ID
     *
     * @return the value of dm_goods_evaluation.GOODS_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_evaluation.GOODS_ID
     *
     * @param goodsId the value for dm_goods_evaluation.GOODS_ID
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_evaluation.TOTAL
     *
     * @return the value of dm_goods_evaluation.TOTAL
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public Integer getTotalCount() {
        return totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_evaluation.TOTAL
     *
     * @param totalCount the value for dm_goods_evaluation.TOTAL
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_evaluation.AVG_SCORE
     *
     * @return the value of dm_goods_evaluation.AVG_SCORE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public Integer getAvgScore() {
        return avgScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_evaluation.AVG_SCORE
     *
     * @param avgScore the value for dm_goods_evaluation.AVG_SCORE
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setAvgScore(Integer avgScore) {
        this.avgScore = avgScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_evaluation.LIKE_COUNT
     *
     * @return the value of dm_goods_evaluation.LIKE_COUNT
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_evaluation.LIKE_COUNT
     *
     * @param likeCount the value for dm_goods_evaluation.LIKE_COUNT
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_evaluation.FAVOURITE_COUNT
     *
     * @return the value of dm_goods_evaluation.FAVOURITE_COUNT
     *
     * @mbggenerated Mon Dec 16 11:00:06 CST 2013
     */
    public Integer getFavouriteCount() {
        return favouriteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_evaluation.FAVOURITE_COUNT
     *
     * @param favouriteCount the value for dm_goods_evaluation.FAVOURITE_COUNT
     *
     * @mbggenerated Mon Dec 16 11:00:06 CST 2013
     */
    public void setFavouriteCount(Integer favouriteCount) {
        this.favouriteCount = favouriteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_evaluation.DISLIKE_COUNT
     *
     * @return the value of dm_goods_evaluation.DISLIKE_COUNT
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public Integer getDislikeCount() {
        return dislikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_evaluation.DISLIKE_COUNT
     *
     * @param dislikeCount the value for dm_goods_evaluation.DISLIKE_COUNT
     *
     * @mbggenerated Mon Dec 16 09:55:59 CST 2013
     */
    public void setDislikeCount(Integer dislikeCount) {
        this.dislikeCount = dislikeCount;
    }
}