package com.qimeng.bs.market.goods.bean;

import org.directwebremoting.annotations.DataTransferObject;

@DataTransferObject
public class DmGoodsInstData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_inst_data.ID
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_inst_data.GOODS_INST_ID
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    private Integer goodsInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_inst_data.PHONE_NO
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    private String phoneNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_inst_data.ID
     *
     * @return the value of dm_goods_inst_data.ID
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_inst_data.ID
     *
     * @param id the value for dm_goods_inst_data.ID
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_inst_data.GOODS_INST_ID
     *
     * @return the value of dm_goods_inst_data.GOODS_INST_ID
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    public Integer getGoodsInstId() {
        return goodsInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_inst_data.GOODS_INST_ID
     *
     * @param goodsInstId the value for dm_goods_inst_data.GOODS_INST_ID
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    public void setGoodsInstId(Integer goodsInstId) {
        this.goodsInstId = goodsInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_inst_data.PHONE_NO
     *
     * @return the value of dm_goods_inst_data.PHONE_NO
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_inst_data.PHONE_NO
     *
     * @param phoneNo the value for dm_goods_inst_data.PHONE_NO
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
}