package com.qimeng.bs.market.goods.bean;

public class DmGoodsInstBaseRel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dm_goods_inst_base_rel.ID
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dm_goods_inst_base_rel.CIRCLE_ID
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	private Integer circleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dm_goods_inst_base_rel.BASE_STATION_ID
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	private Long baseStationId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dm_goods_inst_base_rel.ID
	 * @return  the value of dm_goods_inst_base_rel.ID
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dm_goods_inst_base_rel.ID
	 * @param id  the value for dm_goods_inst_base_rel.ID
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dm_goods_inst_base_rel.CIRCLE_ID
	 * @return  the value of dm_goods_inst_base_rel.CIRCLE_ID
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	public Integer getCircleId() {
		return circleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dm_goods_inst_base_rel.CIRCLE_ID
	 * @param circleId  the value for dm_goods_inst_base_rel.CIRCLE_ID
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	public void setCircleId(Integer circleId) {
		this.circleId = circleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dm_goods_inst_base_rel.BASE_STATION_ID
	 * @return  the value of dm_goods_inst_base_rel.BASE_STATION_ID
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	public Long getBaseStationId() {
		return baseStationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dm_goods_inst_base_rel.BASE_STATION_ID
	 * @param baseStationId  the value for dm_goods_inst_base_rel.BASE_STATION_ID
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	public void setBaseStationId(Long baseStationId) {
		this.baseStationId = baseStationId;
	}
}