package com.qimeng.bs.market.goods.bean;

import org.directwebremoting.annotations.DataTransferObject;

@DataTransferObject
public class DmGoodsInst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_inst.INST_ID
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    private Integer instId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_inst.MERCHANT_ID
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_inst.GOODS_ID
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_inst.GOODS_NAME
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_inst.GOODS_TYPE
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    private String goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_inst.PLAN_ID
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    private Integer planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_inst.PRICE
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_inst.INST_NUM
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    private Integer instNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_inst.STATE
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_inst.INST_ID
     *
     * @return the value of dm_goods_inst.INST_ID
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public Integer getInstId() {
        return instId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_inst.INST_ID
     *
     * @param instId the value for dm_goods_inst.INST_ID
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public void setInstId(Integer instId) {
        this.instId = instId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_inst.MERCHANT_ID
     *
     * @return the value of dm_goods_inst.MERCHANT_ID
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_inst.MERCHANT_ID
     *
     * @param merchantId the value for dm_goods_inst.MERCHANT_ID
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_inst.GOODS_ID
     *
     * @return the value of dm_goods_inst.GOODS_ID
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_inst.GOODS_ID
     *
     * @param goodsId the value for dm_goods_inst.GOODS_ID
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_inst.GOODS_NAME
     *
     * @return the value of dm_goods_inst.GOODS_NAME
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_inst.GOODS_NAME
     *
     * @param goodsName the value for dm_goods_inst.GOODS_NAME
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_inst.GOODS_TYPE
     *
     * @return the value of dm_goods_inst.GOODS_TYPE
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_inst.GOODS_TYPE
     *
     * @param goodsType the value for dm_goods_inst.GOODS_TYPE
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_inst.PLAN_ID
     *
     * @return the value of dm_goods_inst.PLAN_ID
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_inst.PLAN_ID
     *
     * @param planId the value for dm_goods_inst.PLAN_ID
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_inst.PRICE
     *
     * @return the value of dm_goods_inst.PRICE
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_inst.PRICE
     *
     * @param price the value for dm_goods_inst.PRICE
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_inst.INST_NUM
     *
     * @return the value of dm_goods_inst.INST_NUM
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public Integer getInstNum() {
        return instNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_inst.INST_NUM
     *
     * @param instNum the value for dm_goods_inst.INST_NUM
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public void setInstNum(Integer instNum) {
        this.instNum = instNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_inst.STATE
     *
     * @return the value of dm_goods_inst.STATE
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_inst.STATE
     *
     * @param state the value for dm_goods_inst.STATE
     *
     * @mbggenerated Sun Jan 05 18:38:04 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }
}