package com.qimeng.bs.market.goods.bean;

import java.util.Date;

public class DmShoppingCart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_shopping_cart.ID
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_shopping_cart.GOODS_INST_ID
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    private Integer goodsInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_shopping_cart.MERCHANT_ID
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_shopping_cart.ORDER_ID
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_shopping_cart.GOODS_ITEM_NO
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    private Integer goodsItemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_shopping_cart.CTEATE_TIME
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    private Date cteateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_shopping_cart.STATE
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_shopping_cart.ID
     *
     * @return the value of dm_shopping_cart.ID
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_shopping_cart.ID
     *
     * @param id the value for dm_shopping_cart.ID
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_shopping_cart.GOODS_INST_ID
     *
     * @return the value of dm_shopping_cart.GOODS_INST_ID
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public Integer getGoodsInstId() {
        return goodsInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_shopping_cart.GOODS_INST_ID
     *
     * @param goodsInstId the value for dm_shopping_cart.GOODS_INST_ID
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public void setGoodsInstId(Integer goodsInstId) {
        this.goodsInstId = goodsInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_shopping_cart.MERCHANT_ID
     *
     * @return the value of dm_shopping_cart.MERCHANT_ID
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_shopping_cart.MERCHANT_ID
     *
     * @param merchantId the value for dm_shopping_cart.MERCHANT_ID
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_shopping_cart.ORDER_ID
     *
     * @return the value of dm_shopping_cart.ORDER_ID
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_shopping_cart.ORDER_ID
     *
     * @param orderId the value for dm_shopping_cart.ORDER_ID
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_shopping_cart.GOODS_ITEM_NO
     *
     * @return the value of dm_shopping_cart.GOODS_ITEM_NO
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public Integer getGoodsItemNo() {
        return goodsItemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_shopping_cart.GOODS_ITEM_NO
     *
     * @param goodsItemNo the value for dm_shopping_cart.GOODS_ITEM_NO
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public void setGoodsItemNo(Integer goodsItemNo) {
        this.goodsItemNo = goodsItemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_shopping_cart.CTEATE_TIME
     *
     * @return the value of dm_shopping_cart.CTEATE_TIME
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public Date getCteateTime() {
        return cteateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_shopping_cart.CTEATE_TIME
     *
     * @param cteateTime the value for dm_shopping_cart.CTEATE_TIME
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public void setCteateTime(Date cteateTime) {
        this.cteateTime = cteateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_shopping_cart.STATE
     *
     * @return the value of dm_shopping_cart.STATE
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_shopping_cart.STATE
     *
     * @param state the value for dm_shopping_cart.STATE
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    public void setState(String state) {
        this.state = state;
    }
}