package com.qimeng.bs.market.goods.bean;

import java.util.Date;

public class MapElementAttrValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_element_attr_value.E_ID
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    private Integer eId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_element_attr_value.ATTR_CODE
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    private String attrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_element_attr_value.VALUE_SEQ
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    private Integer valueSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_element_attr_value.ATTR_VALUE
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    private String attrValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_element_attr_value.ATTR_TYPE
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    private String attrType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_element_attr_value.CREATE_DATE
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_element_attr_value.CREATE_STAFF
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    private String createStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_element_attr_value.LAT
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_element_attr_value.LNG
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    private String lng;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_element_attr_value.E_ID
     *
     * @return the value of map_element_attr_value.E_ID
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public Integer geteId() {
        return eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_element_attr_value.E_ID
     *
     * @param eId the value for map_element_attr_value.E_ID
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public void seteId(Integer eId) {
        this.eId = eId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_element_attr_value.ATTR_CODE
     *
     * @return the value of map_element_attr_value.ATTR_CODE
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public String getAttrCode() {
        return attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_element_attr_value.ATTR_CODE
     *
     * @param attrCode the value for map_element_attr_value.ATTR_CODE
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public void setAttrCode(String attrCode) {
        this.attrCode = attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_element_attr_value.VALUE_SEQ
     *
     * @return the value of map_element_attr_value.VALUE_SEQ
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public Integer getValueSeq() {
        return valueSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_element_attr_value.VALUE_SEQ
     *
     * @param valueSeq the value for map_element_attr_value.VALUE_SEQ
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public void setValueSeq(Integer valueSeq) {
        this.valueSeq = valueSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_element_attr_value.ATTR_VALUE
     *
     * @return the value of map_element_attr_value.ATTR_VALUE
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_element_attr_value.ATTR_VALUE
     *
     * @param attrValue the value for map_element_attr_value.ATTR_VALUE
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_element_attr_value.ATTR_TYPE
     *
     * @return the value of map_element_attr_value.ATTR_TYPE
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public String getAttrType() {
        return attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_element_attr_value.ATTR_TYPE
     *
     * @param attrType the value for map_element_attr_value.ATTR_TYPE
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public void setAttrType(String attrType) {
        this.attrType = attrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_element_attr_value.CREATE_DATE
     *
     * @return the value of map_element_attr_value.CREATE_DATE
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_element_attr_value.CREATE_DATE
     *
     * @param createDate the value for map_element_attr_value.CREATE_DATE
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_element_attr_value.CREATE_STAFF
     *
     * @return the value of map_element_attr_value.CREATE_STAFF
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public String getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_element_attr_value.CREATE_STAFF
     *
     * @param createStaff the value for map_element_attr_value.CREATE_STAFF
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public void setCreateStaff(String createStaff) {
        this.createStaff = createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_element_attr_value.LAT
     *
     * @return the value of map_element_attr_value.LAT
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_element_attr_value.LAT
     *
     * @param lat the value for map_element_attr_value.LAT
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public void setLat(String lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_element_attr_value.LNG
     *
     * @return the value of map_element_attr_value.LNG
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_element_attr_value.LNG
     *
     * @param lng the value for map_element_attr_value.LNG
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    public void setLng(String lng) {
        this.lng = lng;
    }
}