package com.qimeng.bs.admin.security.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;
@DataTransferObject
public class DmOrganization {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.ORG_ID
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.PARENT_ORG_ID
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private Integer parentOrgId;
    private String isLeaf;
    private Boolean isParent;//非数据库字段
    
    private DmOrganization parentOrg;
    
    private Set<DmOrganization> ChildrenOrgs = new HashSet<DmOrganization>();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.ORG_CODE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.ORG_NAME
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.ORG_LEVEL
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private Integer orgLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.ORG_CONTENT
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private String orgContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.STATUS_CD
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private String statusCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.STATUS_DATE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private Date statusDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.PATH_NAME
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private String pathName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.PATH_CODE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private String pathCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.ORG_TYPE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private String orgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.LAN_ID
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private Integer lanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.BUSINESS_ID
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_organization.CREATE_DATE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.ORG_ID
     *
     * @return the value of dm_organization.ORG_ID
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.ORG_ID
     *
     * @param orgId the value for dm_organization.ORG_ID
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.PARENT_ORG_ID
     *
     * @return the value of dm_organization.PARENT_ORG_ID
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public Integer getParentOrgId() {
        return parentOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.PARENT_ORG_ID
     *
     * @param parentOrgId the value for dm_organization.PARENT_ORG_ID
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setParentOrgId(Integer parentOrgId) {
        this.parentOrgId = parentOrgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.ORG_CODE
     *
     * @return the value of dm_organization.ORG_CODE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.ORG_CODE
     *
     * @param orgCode the value for dm_organization.ORG_CODE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.ORG_NAME
     *
     * @return the value of dm_organization.ORG_NAME
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.ORG_NAME
     *
     * @param orgName the value for dm_organization.ORG_NAME
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.ORG_LEVEL
     *
     * @return the value of dm_organization.ORG_LEVEL
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public Integer getOrgLevel() {
        return orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.ORG_LEVEL
     *
     * @param orgLevel the value for dm_organization.ORG_LEVEL
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setOrgLevel(Integer orgLevel) {
        this.orgLevel = orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.ORG_CONTENT
     *
     * @return the value of dm_organization.ORG_CONTENT
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public String getOrgContent() {
        return orgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.ORG_CONTENT
     *
     * @param orgContent the value for dm_organization.ORG_CONTENT
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setOrgContent(String orgContent) {
        this.orgContent = orgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.STATUS_CD
     *
     * @return the value of dm_organization.STATUS_CD
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.STATUS_CD
     *
     * @param statusCd the value for dm_organization.STATUS_CD
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.STATUS_DATE
     *
     * @return the value of dm_organization.STATUS_DATE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.STATUS_DATE
     *
     * @param statusDate the value for dm_organization.STATUS_DATE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.PATH_NAME
     *
     * @return the value of dm_organization.PATH_NAME
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public String getPathName() {
        return pathName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.PATH_NAME
     *
     * @param pathName the value for dm_organization.PATH_NAME
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setPathName(String pathName) {
        this.pathName = pathName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.PATH_CODE
     *
     * @return the value of dm_organization.PATH_CODE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public String getPathCode() {
        return pathCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.PATH_CODE
     *
     * @param pathCode the value for dm_organization.PATH_CODE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setPathCode(String pathCode) {
        this.pathCode = pathCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.ORG_TYPE
     *
     * @return the value of dm_organization.ORG_TYPE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public String getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.ORG_TYPE
     *
     * @param orgType the value for dm_organization.ORG_TYPE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.LAN_ID
     *
     * @return the value of dm_organization.LAN_ID
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public Integer getLanId() {
        return lanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.LAN_ID
     *
     * @param lanId the value for dm_organization.LAN_ID
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setLanId(Integer lanId) {
        this.lanId = lanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.BUSINESS_ID
     *
     * @return the value of dm_organization.BUSINESS_ID
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.BUSINESS_ID
     *
     * @param businessId the value for dm_organization.BUSINESS_ID
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_organization.CREATE_DATE
     *
     * @return the value of dm_organization.CREATE_DATE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_organization.CREATE_DATE
     *
     * @param createDate the value for dm_organization.CREATE_DATE
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

	public String getIsLeaf() {
		return isLeaf;
	}

	public void setIsLeaf(String isLeaf) {
		this.isLeaf = isLeaf;
	}

	public Boolean getIsParent() {
		return "0".equals(getIsLeaf())?true:false;
	}

	public void setIsParent(Boolean isParent) {
		this.isParent = isParent;
	}

	public DmOrganization getParentOrg() {
		return parentOrg;
	}

	public void setParentOrg(DmOrganization parentOrg) {
		this.parentOrg = parentOrg;
	}

	public Set<DmOrganization> getChildrenOrgs() {
		return ChildrenOrgs;
	}

	public void setChildrenOrgs(Set<DmOrganization> childrenOrgs) {
		ChildrenOrgs = childrenOrgs;
	}
}