package com.qimeng.bs.admin.security.bean;

import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;

import com.qimeng.common.tools.PasswordEncoder;
@DataTransferObject
public class DmStaff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_staff.STAFF_ID
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    private Integer staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_staff.ORG_ID
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_staff.STAFF_CODE
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    private String staffCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_staff.PASSWORD
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_staff.STAFF_NAME
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    private String staffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_staff.GENDER
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_staff.STAFF_DESC
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    private String staffDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_staff.CREATE_DATE
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_staff.EFF_DATE
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    private Date effDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_staff.PARTY_ID
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    private Integer partyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_staff.STATE
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    private String state;
    
    private DmOrganization organization;//所属组织
    
    private Set<DmRole> roles = new HashSet<DmRole>();//角色
    
    private Set<DmPrivilege> privileges = new HashSet<DmPrivilege>();//权限

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_staff.STAFF_ID
     *
     * @return the value of dm_staff.STAFF_ID
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_staff.STAFF_ID
     *
     * @param staffId the value for dm_staff.STAFF_ID
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_staff.ORG_ID
     *
     * @return the value of dm_staff.ORG_ID
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_staff.ORG_ID
     *
     * @param orgId the value for dm_staff.ORG_ID
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_staff.STAFF_CODE
     *
     * @return the value of dm_staff.STAFF_CODE
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public String getStaffCode() {
        return staffCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_staff.STAFF_CODE
     *
     * @param staffCode the value for dm_staff.STAFF_CODE
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public void setStaffCode(String staffCode) {
        this.staffCode = staffCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_staff.PASSWORD
     *
     * @return the value of dm_staff.PASSWORD
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_staff.PASSWORD
     *
     * @param password the value for dm_staff.PASSWORD
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_staff.STAFF_NAME
     *
     * @return the value of dm_staff.STAFF_NAME
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_staff.STAFF_NAME
     *
     * @param staffName the value for dm_staff.STAFF_NAME
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_staff.GENDER
     *
     * @return the value of dm_staff.GENDER
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_staff.GENDER
     *
     * @param gender the value for dm_staff.GENDER
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_staff.STAFF_DESC
     *
     * @return the value of dm_staff.STAFF_DESC
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public String getStaffDesc() {
        return staffDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_staff.STAFF_DESC
     *
     * @param staffDesc the value for dm_staff.STAFF_DESC
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public void setStaffDesc(String staffDesc) {
        this.staffDesc = staffDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_staff.CREATE_DATE
     *
     * @return the value of dm_staff.CREATE_DATE
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_staff.CREATE_DATE
     *
     * @param createDate the value for dm_staff.CREATE_DATE
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_staff.EFF_DATE
     *
     * @return the value of dm_staff.EFF_DATE
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_staff.EFF_DATE
     *
     * @param effDate the value for dm_staff.EFF_DATE
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_staff.PARTY_ID
     *
     * @return the value of dm_staff.PARTY_ID
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public Integer getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_staff.PARTY_ID
     *
     * @param partyId the value for dm_staff.PARTY_ID
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public void setPartyId(Integer partyId) {
        this.partyId = partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_staff.STATE
     *
     * @return the value of dm_staff.STATE
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_staff.STATE
     *
     * @param state the value for dm_staff.STATE
     *
     * @mbggenerated Tue Dec 03 09:53:31 CST 2013
     */
    public void setState(String state) {
        this.state = state;
    }

	public DmOrganization getOrganization() {
		return organization;
	}

	public void setOrganization(DmOrganization organization) {
		this.organization = organization;
	}

	public Set<DmRole> getRoles() {
		return roles;
	}

	public void setRoles(Set<DmRole> roles) {
		this.roles = roles;
	}

	public Set<DmPrivilege> getPrivileges() {
		return privileges;
	}

	public void setPrivileges(Set<DmPrivilege> privileges) {
		this.privileges = privileges;
	}
	
    public DmStaff encodePassword(){
    	String encodingPassword = PasswordEncoder.encode(getPassword(), getStaffCode());
        setPassword(encodingPassword);
    	return this;
    }
}