package com.qimeng.bs.market.point.dao;

import com.qimeng.common.Page;
import com.qimeng.bs.market.point.bean.DmPoints;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DmPointsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_points
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    int deleteByPrimaryKey(Integer pointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_points
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    int insert(DmPoints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_points
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    int insertSelective(DmPoints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_points
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    DmPoints selectByPrimaryKey(Integer pointId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_points
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    int updateByPrimaryKeySelective(DmPoints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_points
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    int updateByPrimaryKey(DmPoints record);
    
    int selectEffPointByMerchantId(Integer merchantId);
    
    List<DmPoints> findAllPoint(Page<DmPoints> page);
}