package com.qimeng.bs.admin.inte.bean;

import org.directwebremoting.annotations.DataTransferObject;

@DataTransferObject
public class SystemInterface {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_interface.INTERFACE_ID
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    private Integer interfaceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_interface.INTERFACE_CODE
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    private String interfaceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_interface.INTERFACE_NAME
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    private String interfaceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_interface.INTERFACE_TYPE
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    private String interfaceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_interface.URL
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_interface.STATE
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_interface.INTERFACE_ID
     *
     * @return the value of system_interface.INTERFACE_ID
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    public Integer getInterfaceId() {
        return interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_interface.INTERFACE_ID
     *
     * @param interfaceId the value for system_interface.INTERFACE_ID
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    public void setInterfaceId(Integer interfaceId) {
        this.interfaceId = interfaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_interface.INTERFACE_CODE
     *
     * @return the value of system_interface.INTERFACE_CODE
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    public String getInterfaceCode() {
        return interfaceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_interface.INTERFACE_CODE
     *
     * @param interfaceCode the value for system_interface.INTERFACE_CODE
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    public void setInterfaceCode(String interfaceCode) {
        this.interfaceCode = interfaceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_interface.INTERFACE_NAME
     *
     * @return the value of system_interface.INTERFACE_NAME
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_interface.INTERFACE_NAME
     *
     * @param interfaceName the value for system_interface.INTERFACE_NAME
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_interface.INTERFACE_TYPE
     *
     * @return the value of system_interface.INTERFACE_TYPE
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    public String getInterfaceType() {
        return interfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_interface.INTERFACE_TYPE
     *
     * @param interfaceType the value for system_interface.INTERFACE_TYPE
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    public void setInterfaceType(String interfaceType) {
        this.interfaceType = interfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_interface.URL
     *
     * @return the value of system_interface.URL
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_interface.URL
     *
     * @param url the value for system_interface.URL
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_interface.STATE
     *
     * @return the value of system_interface.STATE
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_interface.STATE
     *
     * @param state the value for system_interface.STATE
     *
     * @mbggenerated Mon Jan 13 16:17:05 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }
}