package com.qimeng.bs.admin.goods.bean;

import org.directwebremoting.annotations.DataTransferObject;

@DataTransferObject
public class DmAdvertisement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_advertisement.ID
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_advertisement.GOODS_ID
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    private Integer goodsId;
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_advertisement.AD_NAME
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    private String adName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_advertisement.IMAGE_URL
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_advertisement.AD_DESC
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    private String adDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_advertisement.AD_LEVEL
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    private String adLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_advertisement.AD_ORDER
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    private Integer adOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_advertisement.ID
     *
     * @return the value of dm_advertisement.ID
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_advertisement.ID
     *
     * @param id the value for dm_advertisement.ID
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_advertisement.GOODS_ID
     *
     * @return the value of dm_advertisement.GOODS_ID
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_advertisement.GOODS_ID
     *
     * @param goodsId the value for dm_advertisement.GOODS_ID
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_advertisement.AD_NAME
     *
     * @return the value of dm_advertisement.AD_NAME
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public String getAdName() {
        return adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_advertisement.AD_NAME
     *
     * @param adName the value for dm_advertisement.AD_NAME
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public void setAdName(String adName) {
        this.adName = adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_advertisement.IMAGE_URL
     *
     * @return the value of dm_advertisement.IMAGE_URL
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_advertisement.IMAGE_URL
     *
     * @param imageUrl the value for dm_advertisement.IMAGE_URL
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_advertisement.AD_DESC
     *
     * @return the value of dm_advertisement.AD_DESC
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public String getAdDesc() {
        return adDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_advertisement.AD_DESC
     *
     * @param adDesc the value for dm_advertisement.AD_DESC
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public void setAdDesc(String adDesc) {
        this.adDesc = adDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_advertisement.AD_LEVEL
     *
     * @return the value of dm_advertisement.AD_LEVEL
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public String getAdLevel() {
        return adLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_advertisement.AD_LEVEL
     *
     * @param adLevel the value for dm_advertisement.AD_LEVEL
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public void setAdLevel(String adLevel) {
        this.adLevel = adLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_advertisement.AD_ORDER
     *
     * @return the value of dm_advertisement.AD_ORDER
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public Integer getAdOrder() {
        return adOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_advertisement.AD_ORDER
     *
     * @param adOrder the value for dm_advertisement.AD_ORDER
     *
     * @mbggenerated Fri Dec 27 09:39:36 CST 2013
     */
    public void setAdOrder(Integer adOrder) {
        this.adOrder = adOrder;
    }

	public String getGoodsName() {
		return goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}
}