package com.qimeng.bs.admin.goods.bean;

import org.directwebremoting.annotations.DataTransferObject;
import org.springframework.util.StringUtils;

import java.util.Date;
@DataTransferObject
public class DmGoodsPlan {
    public static final String GOODTYPE_VAL1 = "1";//商品
    public static final String GOODTYPE_VAL2 = "2";//商品包
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.PLAN_ID
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private Integer planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.GOODS_ID
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private Integer goodsId;
    private String goodName;
    
    private DmGoodsPackage dmGoodsPackage;
    private DmGoods dmGoods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.GOODS_TYPE
     *
     * @mbggenerated Wed Dec 25 14:44:37 CST 2013
     */
    private String goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.PLAN_NAME
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private String planName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.PLAN_INTRO
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private String planIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.PLAN_PRICE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private Float planPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.PLAN_SHOW_PRICE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private Float planShowPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.PLAN_DESC
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private String planDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.EFF_DATE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private Date effDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.EXP_DATE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private Date expDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.STATE_DATE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private Date stateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.OPER_STAFF_ID
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private String operStaffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.OPER_STAFF_NAME
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private String operStaffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.PLAN_TYPE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private String planType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_plan.STATE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.PLAN_ID
     *
     * @return the value of dm_goods_plan.PLAN_ID
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.PLAN_ID
     *
     * @param planId the value for dm_goods_plan.PLAN_ID
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.GOODS_ID
     *
     * @return the value of dm_goods_plan.GOODS_ID
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.GOODS_ID
     *
     * @param goodsId the value for dm_goods_plan.GOODS_ID
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.GOODS_TYPE
     *
     * @return the value of dm_goods_plan.GOODS_TYPE
     *
     * @mbggenerated Wed Dec 25 14:44:37 CST 2013
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.GOODS_TYPE
     *
     * @param goodsType the value for dm_goods_plan.GOODS_TYPE
     *
     * @mbggenerated Wed Dec 25 14:44:37 CST 2013
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.PLAN_NAME
     *
     * @return the value of dm_goods_plan.PLAN_NAME
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.PLAN_NAME
     *
     * @param planName the value for dm_goods_plan.PLAN_NAME
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setPlanName(String planName) {
        this.planName = planName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.PLAN_INTRO
     *
     * @return the value of dm_goods_plan.PLAN_INTRO
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public String getPlanIntro() {
        return planIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.PLAN_INTRO
     *
     * @param planIntro the value for dm_goods_plan.PLAN_INTRO
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setPlanIntro(String planIntro) {
        this.planIntro = planIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.PLAN_PRICE
     *
     * @return the value of dm_goods_plan.PLAN_PRICE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public Float getPlanPrice() {
        return planPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.PLAN_PRICE
     *
     * @param planPrice the value for dm_goods_plan.PLAN_PRICE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setPlanPrice(Float planPrice) {
        this.planPrice = planPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.PLAN_SHOW_PRICE
     *
     * @return the value of dm_goods_plan.PLAN_SHOW_PRICE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public Float getPlanShowPrice() {
        return planShowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.PLAN_SHOW_PRICE
     *
     * @param planShowPrice the value for dm_goods_plan.PLAN_SHOW_PRICE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setPlanShowPrice(Float planShowPrice) {
        this.planShowPrice = planShowPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.PLAN_DESC
     *
     * @return the value of dm_goods_plan.PLAN_DESC
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public String getPlanDesc() {
        return planDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.PLAN_DESC
     *
     * @param planDesc the value for dm_goods_plan.PLAN_DESC
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setPlanDesc(String planDesc) {
        this.planDesc = planDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.EFF_DATE
     *
     * @return the value of dm_goods_plan.EFF_DATE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.EFF_DATE
     *
     * @param effDate the value for dm_goods_plan.EFF_DATE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.EXP_DATE
     *
     * @return the value of dm_goods_plan.EXP_DATE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.EXP_DATE
     *
     * @param expDate the value for dm_goods_plan.EXP_DATE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.STATE_DATE
     *
     * @return the value of dm_goods_plan.STATE_DATE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.STATE_DATE
     *
     * @param stateDate the value for dm_goods_plan.STATE_DATE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.OPER_STAFF_ID
     *
     * @return the value of dm_goods_plan.OPER_STAFF_ID
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public String getOperStaffId() {
        return operStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.OPER_STAFF_ID
     *
     * @param operStaffId the value for dm_goods_plan.OPER_STAFF_ID
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setOperStaffId(String operStaffId) {
        this.operStaffId = operStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.OPER_STAFF_NAME
     *
     * @return the value of dm_goods_plan.OPER_STAFF_NAME
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public String getOperStaffName() {
        return operStaffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.OPER_STAFF_NAME
     *
     * @param operStaffName the value for dm_goods_plan.OPER_STAFF_NAME
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setOperStaffName(String operStaffName) {
        this.operStaffName = operStaffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.PLAN_TYPE
     *
     * @return the value of dm_goods_plan.PLAN_TYPE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public String getPlanType() {
        return planType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.PLAN_TYPE
     *
     * @param planType the value for dm_goods_plan.PLAN_TYPE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setPlanType(String planType) {
        this.planType = planType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_plan.STATE
     *
     * @return the value of dm_goods_plan.STATE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public String getState() {
        return state;
    }

    public String getGoodName() {
      if(!StringUtils.isEmpty(this.goodsType)){
        if(GOODTYPE_VAL1.equals(this.goodsType)){
          if(this.dmGoods!=null){
            this.setGoodName(this.dmGoods.getGoodsName());
          }
        }else if(GOODTYPE_VAL2.equals(this.goodsType)){
          if(this.dmGoodsPackage!=null){
            this.setGoodName(this.dmGoodsPackage.getPackageName());
          }
        }
      }
      return this.goodName;
    }

    public void setGoodName(String goodName) {
      this.goodName = goodName;
    }

    public DmGoodsPackage getDmGoodsPackage() {
      return dmGoodsPackage;
    }

    public void setDmGoodsPackage(DmGoodsPackage dmGoodsPackage) {
      this.dmGoodsPackage = dmGoodsPackage;
    }

    public DmGoods getDmGoods() {
      return dmGoods;
    }

    public void setDmGoods(DmGoods dmGoods) {
      this.dmGoods = dmGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_plan.STATE
     *
     * @param state the value for dm_goods_plan.STATE
     *
     * @mbggenerated Mon Dec 23 15:07:49 CST 2013
     */
    public void setState(String state) {
        this.state = state;
    }
}