package com.qimeng.bs.admin.goods.bean;

import org.directwebremoting.annotations.DataTransferObject;

@DataTransferObject
public class DmGoodsTag {
	
	public DmGoodsTag(){};
	
	public DmGoodsTag(Integer tagId,Integer goodsId){
		this.tagId = tagId;
		this.goodsId = goodsId;
	}
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_tag.TAG_GROUP_ID
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    private Integer tagGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_tag.TAG_ID
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_tag.GOODS_ID
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_tag.TAG_GROUP_ID
     *
     * @return the value of dm_goods_tag.TAG_GROUP_ID
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    public Integer getTagGroupId() {
        return tagGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_tag.TAG_GROUP_ID
     *
     * @param tagGroupId the value for dm_goods_tag.TAG_GROUP_ID
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    public void setTagGroupId(Integer tagGroupId) {
        this.tagGroupId = tagGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_tag.TAG_ID
     *
     * @return the value of dm_goods_tag.TAG_ID
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_tag.TAG_ID
     *
     * @param tagId the value for dm_goods_tag.TAG_ID
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_tag.GOODS_ID
     *
     * @return the value of dm_goods_tag.GOODS_ID
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_tag.GOODS_ID
     *
     * @param goodsId the value for dm_goods_tag.GOODS_ID
     *
     * @mbggenerated Wed Dec 18 09:42:02 CST 2013
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }
}