package com.qimeng.bs.admin.goods.bean;

import org.directwebremoting.annotations.DataTransferObject;

@DataTransferObject
public class DmGoodsTagValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_tag_value.TAG_VALUE_ID
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    private Integer tagValueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_tag_value.TAG_GROUP_ID
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    private Integer tagGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_tag_value.ITEM_ID
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_tag_value.TAG_VALUE_ID
     *
     * @return the value of dm_goods_tag_value.TAG_VALUE_ID
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    public Integer getTagValueId() {
        return tagValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_tag_value.TAG_VALUE_ID
     *
     * @param tagValueId the value for dm_goods_tag_value.TAG_VALUE_ID
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    public void setTagValueId(Integer tagValueId) {
        this.tagValueId = tagValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_tag_value.TAG_GROUP_ID
     *
     * @return the value of dm_goods_tag_value.TAG_GROUP_ID
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    public Integer getTagGroupId() {
        return tagGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_tag_value.TAG_GROUP_ID
     *
     * @param tagGroupId the value for dm_goods_tag_value.TAG_GROUP_ID
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    public void setTagGroupId(Integer tagGroupId) {
        this.tagGroupId = tagGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_tag_value.ITEM_ID
     *
     * @return the value of dm_goods_tag_value.ITEM_ID
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_tag_value.ITEM_ID
     *
     * @param itemId the value for dm_goods_tag_value.ITEM_ID
     *
     * @mbggenerated Wed Dec 18 09:58:01 CST 2013
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
}