package com.qimeng.bs.admin.goods.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.directwebremoting.annotations.DataTransferObject;
@DataTransferObject
public class DmGoodsPackage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_package.PACKAGE_ID
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    private Integer packageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_package.PACKAGE_CODE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    private String packageCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_package.PLAN_ID
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    private Integer planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_package.PACKAGE_NAME
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    private String packageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_package.PACKAGE_DESC
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    private String packageDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_package.STATE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_package.EFF_DATE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    private Date effDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_package.EXP_DATE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    private Date expDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_goods_package.CREATE_DATE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    private Date createDate;
    
    private Set<DmGoods> dmGoods = new HashSet<DmGoods>(); 

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_package.PACKAGE_ID
     *
     * @return the value of dm_goods_package.PACKAGE_ID
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public Integer getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_package.PACKAGE_ID
     *
     * @param packageId the value for dm_goods_package.PACKAGE_ID
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public void setPackageId(Integer packageId) {
        this.packageId = packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_package.PACKAGE_CODE
     *
     * @return the value of dm_goods_package.PACKAGE_CODE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public String getPackageCode() {
        return packageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_package.PACKAGE_CODE
     *
     * @param packageCode the value for dm_goods_package.PACKAGE_CODE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public void setPackageCode(String packageCode) {
        this.packageCode = packageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_package.PLAN_ID
     *
     * @return the value of dm_goods_package.PLAN_ID
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_package.PLAN_ID
     *
     * @param planId the value for dm_goods_package.PLAN_ID
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_package.PACKAGE_NAME
     *
     * @return the value of dm_goods_package.PACKAGE_NAME
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_package.PACKAGE_NAME
     *
     * @param packageName the value for dm_goods_package.PACKAGE_NAME
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_package.PACKAGE_DESC
     *
     * @return the value of dm_goods_package.PACKAGE_DESC
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public String getPackageDesc() {
        return packageDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_package.PACKAGE_DESC
     *
     * @param packageDesc the value for dm_goods_package.PACKAGE_DESC
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public void setPackageDesc(String packageDesc) {
        this.packageDesc = packageDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_package.STATE
     *
     * @return the value of dm_goods_package.STATE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_package.STATE
     *
     * @param state the value for dm_goods_package.STATE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_package.EFF_DATE
     *
     * @return the value of dm_goods_package.EFF_DATE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_package.EFF_DATE
     *
     * @param effDate the value for dm_goods_package.EFF_DATE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_package.EXP_DATE
     *
     * @return the value of dm_goods_package.EXP_DATE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_package.EXP_DATE
     *
     * @param expDate the value for dm_goods_package.EXP_DATE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_goods_package.CREATE_DATE
     *
     * @return the value of dm_goods_package.CREATE_DATE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_goods_package.CREATE_DATE
     *
     * @param createDate the value for dm_goods_package.CREATE_DATE
     *
     * @mbggenerated Wed Dec 25 16:31:44 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

	public Set<DmGoods> getDmGoods() {
		return dmGoods;
	}

	public void setDmGoods(Set<DmGoods> dmGoods) {
		this.dmGoods = dmGoods;
	}
}