package com.qimeng.bs.admin.goods.bean;

import org.directwebremoting.annotations.DataTransferObject;

@DataTransferObject
public class DmTagsItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_tags_item.ITEM_ID
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_tags_item.TAG_ID
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_tags_item.ITEM_VALUE
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    private String itemValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_tags_item.ITEM_DESC
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    private String itemDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_tags_item.ORDER_ID
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    private Integer orderId;
    
    private DmTags dmtag;
    
    private String checked;
    
    private Integer tagGroupId = -1;//商品与标签关联主键id

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_tags_item.ITEM_ID
     *
     * @return the value of dm_tags_item.ITEM_ID
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_tags_item.ITEM_ID
     *
     * @param itemId the value for dm_tags_item.ITEM_ID
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_tags_item.TAG_ID
     *
     * @return the value of dm_tags_item.TAG_ID
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_tags_item.TAG_ID
     *
     * @param tagId the value for dm_tags_item.TAG_ID
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_tags_item.ITEM_VALUE
     *
     * @return the value of dm_tags_item.ITEM_VALUE
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    public String getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_tags_item.ITEM_VALUE
     *
     * @param itemValue the value for dm_tags_item.ITEM_VALUE
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    public void setItemValue(String itemValue) {
        this.itemValue = itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_tags_item.ITEM_DESC
     *
     * @return the value of dm_tags_item.ITEM_DESC
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_tags_item.ITEM_DESC
     *
     * @param itemDesc the value for dm_tags_item.ITEM_DESC
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_tags_item.ORDER_ID
     *
     * @return the value of dm_tags_item.ORDER_ID
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_tags_item.ORDER_ID
     *
     * @param orderId the value for dm_tags_item.ORDER_ID
     *
     * @mbggenerated Thu Dec 12 10:10:56 CST 2013
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

	public DmTags getDmtag() {
		return dmtag;
	}

	public void setDmtag(DmTags dmtag) {
		this.dmtag = dmtag;
	}
	
	public String getChecked() {
		if(tagGroupId!=-1){
			setChecked("true");
		}else{
			setChecked("false");
		}
        return checked;
	}

	public void setChecked(String checked) {
		this.checked = checked;
	}

	public Integer getTagGroupId() {
		return tagGroupId;
	}

	public void setTagGroupId(Integer tagGroupId) {
		this.tagGroupId = tagGroupId;
	}
}