package com.qimeng.bs.market.goods.dao;

import com.qimeng.bs.market.goods.bean.DmBizCircle;
import org.springframework.stereotype.Repository;

@Repository
public interface DmBizCircleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_biz_circle
     *
     * @mbggenerated Tue Dec 24 14:34:35 CST 2013
     */
    int deleteByPrimaryKey(Integer circleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_biz_circle
     *
     * @mbggenerated Tue Dec 24 14:34:35 CST 2013
     */
    int insert(DmBizCircle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_biz_circle
     *
     * @mbggenerated Tue Dec 24 14:34:35 CST 2013
     */
    int insertSelective(DmBizCircle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_biz_circle
     *
     * @mbggenerated Tue Dec 24 14:34:35 CST 2013
     */
    DmBizCircle selectByPrimaryKey(Integer circleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_biz_circle
     *
     * @mbggenerated Tue Dec 24 14:34:35 CST 2013
     */
    int updateByPrimaryKeySelective(DmBizCircle record);

    int updateInstIdByPrimaryKey(DmBizCircle record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_biz_circle
     *
     * @mbggenerated Tue Dec 24 14:34:35 CST 2013
     */
    int updateByPrimaryKey(DmBizCircle record);
}