package com.qimeng.bs.market.goods.dao;

import com.qimeng.bs.market.goods.bean.DmGoodsInstTagItem;
import org.springframework.stereotype.Repository;

@Repository
public interface DmGoodsInstTagItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst_tag_item
     *
     * @mbggenerated Thu Dec 12 15:38:59 CST 2013
     */
    int deleteByPrimaryKey(Integer instTagItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst_tag_item
     *
     * @mbggenerated Thu Dec 12 15:38:59 CST 2013
     */
    int insert(DmGoodsInstTagItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst_tag_item
     *
     * @mbggenerated Thu Dec 12 15:38:59 CST 2013
     */
    int insertSelective(DmGoodsInstTagItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst_tag_item
     *
     * @mbggenerated Thu Dec 12 15:38:59 CST 2013
     */
    DmGoodsInstTagItem selectByPrimaryKey(Integer instTagItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst_tag_item
     *
     * @mbggenerated Thu Dec 12 15:38:59 CST 2013
     */
    int updateByPrimaryKeySelective(DmGoodsInstTagItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst_tag_item
     *
     * @mbggenerated Thu Dec 12 15:38:59 CST 2013
     */
    int updateByPrimaryKey(DmGoodsInstTagItem record);
}