package com.qimeng.bs.market.goods.dao;

import com.qimeng.bs.market.goods.bean.DmGoodsInstData;
import org.springframework.stereotype.Repository;

@Repository
public interface DmGoodsInstDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst_data
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst_data
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    int insert(DmGoodsInstData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst_data
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    int insertSelective(DmGoodsInstData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst_data
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    DmGoodsInstData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst_data
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    int updateByPrimaryKeySelective(DmGoodsInstData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst_data
     *
     * @mbggenerated Wed Dec 04 15:39:54 CST 2013
     */
    int updateByPrimaryKey(DmGoodsInstData record);
}