package com.qimeng.bs.market.goods.dao;

import com.qimeng.bs.market.goods.bean.DmGoodsInst;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface DmGoodsInstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst
     *
     * @mbggenerated Tue Dec 10 11:29:07 CST 2013
     */
    int deleteByPrimaryKey(Integer instId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst
     *
     * @mbggenerated Tue Dec 10 11:29:07 CST 2013
     */
    int insert(DmGoodsInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst
     *
     * @mbggenerated Tue Dec 10 11:29:07 CST 2013
     */
    int insertSelective(DmGoodsInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst
     *
     * @mbggenerated Tue Dec 10 11:29:07 CST 2013
     */
    DmGoodsInst selectByPrimaryKey(Integer instId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst
     *
     * @mbggenerated Tue Dec 10 11:29:07 CST 2013
     */
    int updateByPrimaryKeySelective(DmGoodsInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_goods_inst
     *
     * @mbggenerated Tue Dec 10 11:29:07 CST 2013
     */
    int updateByPrimaryKey(DmGoodsInst record);

    List<DmGoodsInst> queryAvailableGoodsInst(Map params);

    DmGoodsInst selectGoodsInstAndPrice(Integer instId);
}