package com.qimeng.bs.market.goods.dao;

import com.qimeng.bs.market.goods.bean.DmGoodsInstBaseRel;

public interface DmGoodsInstBaseRelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dm_goods_inst_base_rel
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	int deleteByPrimaryKey(Integer id);
	int deleteByCircleId(Integer circleId);
	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dm_goods_inst_base_rel
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	int insert(DmGoodsInstBaseRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dm_goods_inst_base_rel
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	int insertSelective(DmGoodsInstBaseRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dm_goods_inst_base_rel
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	DmGoodsInstBaseRel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dm_goods_inst_base_rel
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	int updateByPrimaryKeySelective(DmGoodsInstBaseRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dm_goods_inst_base_rel
	 * @mbggenerated  Tue Dec 24 17:22:14 CST 2013
	 */
	int updateByPrimaryKey(DmGoodsInstBaseRel record);
}