package com.qimeng.bs.market.goods.dao;

import com.qimeng.bs.market.goods.bean.DmGoodsInst;
import com.qimeng.bs.market.goods.bean.DmShoppingCartItem;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DmShoppingCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_shopping_cart
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_shopping_cart
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    int insert(DmShoppingCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_shopping_cart
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    int insertSelective(DmShoppingCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_shopping_cart
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    DmShoppingCartItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_shopping_cart
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    int updateByPrimaryKeySelective(DmShoppingCartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_shopping_cart
     *
     * @mbggenerated Thu Dec 19 16:21:31 CST 2013
     */
    int updateByPrimaryKey(DmShoppingCartItem record);

//    List<DmGoodsInst> selectGoodsInstInCart(int merchantId);


    void removeGoodsInCart(Integer goodsId);

    void batchRemoveGoodsInCart(List<Integer> instList);

    void removeGoodsInCartByMerchantId(int merchantId);

    List<DmShoppingCartItem> selectShoppingCartItemsByMerchantId(int merchantId);

}