package com.qimeng.bs.market.goods.dao;

import com.qimeng.bs.market.goods.bean.MapElementAttrValue;

public interface MapElementAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_element_attr_value
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    int insert(MapElementAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_element_attr_value
     *
     * @mbggenerated Tue Dec 24 15:10:21 CST 2013
     */
    int insertSelective(MapElementAttrValue record);
}