package com.qimeng.bs.market.goods.dao;

import com.qimeng.bs.market.goods.bean.MapElement;

public interface MapElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_element
     *
     * @mbggenerated Tue Dec 24 14:52:49 CST 2013
     */
    int deleteByPrimaryKey(Integer eId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_element
     *
     * @mbggenerated Tue Dec 24 14:52:49 CST 2013
     */
    int insert(MapElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_element
     *
     * @mbggenerated Tue Dec 24 14:52:49 CST 2013
     */
    int insertSelective(MapElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_element
     *
     * @mbggenerated Tue Dec 24 14:52:49 CST 2013
     */
    MapElement selectByPrimaryKey(Integer eId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_element
     *
     * @mbggenerated Tue Dec 24 14:52:49 CST 2013
     */
    int updateByPrimaryKeySelective(MapElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_element
     *
     * @mbggenerated Tue Dec 24 14:52:49 CST 2013
     */
    int updateByPrimaryKey(MapElement record);
}