package com.qimeng.bs.admin.notice.bean;

import java.util.Date;

import org.directwebremoting.annotations.DataTransferObject;

@DataTransferObject
public class DmNotice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_notice.NOTICE_ID
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    private Integer noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_notice.NOTICE_TITLE
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    private String noticeTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_notice.NOTICE_DEST
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    private String noticeDest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_notice.NOTICE_CONTEXT
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    private String noticeContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_notice.STATE
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_notice.CREATE_DATE
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_notice.ORDER_ID
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_notice.PUBLISHER
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_notice.PUBLISH_TIME
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    private Date publishTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_notice.NOTICE_ID
     *
     * @return the value of dm_notice.NOTICE_ID
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_notice.NOTICE_ID
     *
     * @param noticeId the value for dm_notice.NOTICE_ID
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_notice.NOTICE_TITLE
     *
     * @return the value of dm_notice.NOTICE_TITLE
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public String getNoticeTitle() {
        return noticeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_notice.NOTICE_TITLE
     *
     * @param noticeTitle the value for dm_notice.NOTICE_TITLE
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public void setNoticeTitle(String noticeTitle) {
        this.noticeTitle = noticeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_notice.NOTICE_DEST
     *
     * @return the value of dm_notice.NOTICE_DEST
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public String getNoticeDest() {
        return noticeDest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_notice.NOTICE_DEST
     *
     * @param noticeDest the value for dm_notice.NOTICE_DEST
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public void setNoticeDest(String noticeDest) {
        this.noticeDest = noticeDest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_notice.NOTICE_CONTEXT
     *
     * @return the value of dm_notice.NOTICE_CONTEXT
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public String getNoticeContext() {
        return noticeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_notice.NOTICE_CONTEXT
     *
     * @param noticeContext the value for dm_notice.NOTICE_CONTEXT
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public void setNoticeContext(String noticeContext) {
        this.noticeContext = noticeContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_notice.STATE
     *
     * @return the value of dm_notice.STATE
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_notice.STATE
     *
     * @param state the value for dm_notice.STATE
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_notice.CREATE_DATE
     *
     * @return the value of dm_notice.CREATE_DATE
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_notice.CREATE_DATE
     *
     * @param createDate the value for dm_notice.CREATE_DATE
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_notice.ORDER_ID
     *
     * @return the value of dm_notice.ORDER_ID
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_notice.ORDER_ID
     *
     * @param orderId the value for dm_notice.ORDER_ID
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_notice.PUBLISHER
     *
     * @return the value of dm_notice.PUBLISHER
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_notice.PUBLISHER
     *
     * @param publisher the value for dm_notice.PUBLISHER
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_notice.PUBLISH_TIME
     *
     * @return the value of dm_notice.PUBLISH_TIME
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_notice.PUBLISH_TIME
     *
     * @param publishTime the value for dm_notice.PUBLISH_TIME
     *
     * @mbggenerated Thu Jan 16 15:16:23 CST 2014
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }
}