package com.qimeng.bs.admin.merchant.bean;

import java.util.Date;

import org.directwebremoting.annotations.DataTransferObject;

@DataTransferObject
public class DmMerchantFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_file.ID
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_file.MERCHANT_ID
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_file.NAME
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_file.TYPE
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_file.URI
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_file.CREATE_DATE
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_file.STATE
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant_file.STATE_DATE
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    private Date stateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_file.ID
     *
     * @return the value of dm_merchant_file.ID
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_file.ID
     *
     * @param id the value for dm_merchant_file.ID
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_file.MERCHANT_ID
     *
     * @return the value of dm_merchant_file.MERCHANT_ID
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_file.MERCHANT_ID
     *
     * @param merchantId the value for dm_merchant_file.MERCHANT_ID
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_file.NAME
     *
     * @return the value of dm_merchant_file.NAME
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_file.NAME
     *
     * @param name the value for dm_merchant_file.NAME
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_file.TYPE
     *
     * @return the value of dm_merchant_file.TYPE
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_file.TYPE
     *
     * @param type the value for dm_merchant_file.TYPE
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_file.URI
     *
     * @return the value of dm_merchant_file.URI
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_file.URI
     *
     * @param uri the value for dm_merchant_file.URI
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public void setUri(String uri) {
        this.uri = uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_file.CREATE_DATE
     *
     * @return the value of dm_merchant_file.CREATE_DATE
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_file.CREATE_DATE
     *
     * @param createDate the value for dm_merchant_file.CREATE_DATE
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_file.STATE
     *
     * @return the value of dm_merchant_file.STATE
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_file.STATE
     *
     * @param state the value for dm_merchant_file.STATE
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant_file.STATE_DATE
     *
     * @return the value of dm_merchant_file.STATE_DATE
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant_file.STATE_DATE
     *
     * @param stateDate the value for dm_merchant_file.STATE_DATE
     *
     * @mbggenerated Mon Dec 09 15:07:26 CST 2013
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }
}