package com.qimeng.bs.admin.merchant.bean;

import java.util.Date;

import org.directwebremoting.annotations.DataTransferObject;

import javax.ws.rs.FormParam;

@DataTransferObject
public class DmMerchant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.MERCHANT_ID
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.USER_ID
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.MERCHANT_CODE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String merchantCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.MERCHANT_NAME
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.GENDER
     *
     * @mbggenerated Sat Jan 04 15:59:50 CST 2014
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.KIND
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.LEVEL
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.PROVINCE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.CITY
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.DISTRICT
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.ADDRESS
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.MERCHANT_DESC
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String merchantDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.LEGAL_PERSON
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String legalPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.LEGAL_CERT_TYPE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    @FormParam("cardType")
    private String legalCertType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.LEGAL_CERT_NO
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    @FormParam("cardNo")
    private String legalCertNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.LICENSES_NO
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String licensesNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.TAX_NO
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String taxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.REGISTER_DATE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.STATE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.CREATE_DATE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.STATE_DATE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private Date stateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_merchant.MERCHANT_TYPE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    private String merchantType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.MERCHANT_ID
     *
     * @return the value of dm_merchant.MERCHANT_ID
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.MERCHANT_ID
     *
     * @param merchantId the value for dm_merchant.MERCHANT_ID
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.USER_ID
     *
     * @return the value of dm_merchant.USER_ID
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.USER_ID
     *
     * @param userId the value for dm_merchant.USER_ID
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.MERCHANT_CODE
     *
     * @return the value of dm_merchant.MERCHANT_CODE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.MERCHANT_CODE
     *
     * @param merchantCode the value for dm_merchant.MERCHANT_CODE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.MERCHANT_NAME
     *
     * @return the value of dm_merchant.MERCHANT_NAME
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.MERCHANT_NAME
     *
     * @param merchantName the value for dm_merchant.MERCHANT_NAME
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.GENDER
     *
     * @return the value of dm_merchant.GENDER
     *
     * @mbggenerated Sat Jan 04 15:59:50 CST 2014
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.GENDER
     *
     * @param gender the value for dm_merchant.GENDER
     *
     * @mbggenerated Sat Jan 04 15:59:50 CST 2014
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.KIND
     *
     * @return the value of dm_merchant.KIND
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.KIND
     *
     * @param kind the value for dm_merchant.KIND
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setKind(String kind) {
        this.kind = kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.LEVEL
     *
     * @return the value of dm_merchant.LEVEL
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.LEVEL
     *
     * @param level the value for dm_merchant.LEVEL
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.PROVINCE
     *
     * @return the value of dm_merchant.PROVINCE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.PROVINCE
     *
     * @param province the value for dm_merchant.PROVINCE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.CITY
     *
     * @return the value of dm_merchant.CITY
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.CITY
     *
     * @param city the value for dm_merchant.CITY
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.DISTRICT
     *
     * @return the value of dm_merchant.DISTRICT
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.DISTRICT
     *
     * @param district the value for dm_merchant.DISTRICT
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setDistrict(String district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.ADDRESS
     *
     * @return the value of dm_merchant.ADDRESS
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.ADDRESS
     *
     * @param address the value for dm_merchant.ADDRESS
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.MERCHANT_DESC
     *
     * @return the value of dm_merchant.MERCHANT_DESC
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getMerchantDesc() {
        return merchantDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.MERCHANT_DESC
     *
     * @param merchantDesc the value for dm_merchant.MERCHANT_DESC
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setMerchantDesc(String merchantDesc) {
        this.merchantDesc = merchantDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.LEGAL_PERSON
     *
     * @return the value of dm_merchant.LEGAL_PERSON
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.LEGAL_PERSON
     *
     * @param legalPerson the value for dm_merchant.LEGAL_PERSON
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.LEGAL_CERT_TYPE
     *
     * @return the value of dm_merchant.LEGAL_CERT_TYPE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getLegalCertType() {
        return legalCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.LEGAL_CERT_TYPE
     *
     * @param legalCertType the value for dm_merchant.LEGAL_CERT_TYPE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setLegalCertType(String legalCertType) {
        this.legalCertType = legalCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.LEGAL_CERT_NO
     *
     * @return the value of dm_merchant.LEGAL_CERT_NO
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getLegalCertNo() {
        return legalCertNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.LEGAL_CERT_NO
     *
     * @param legalCertNo the value for dm_merchant.LEGAL_CERT_NO
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setLegalCertNo(String legalCertNo) {
        this.legalCertNo = legalCertNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.LICENSES_NO
     *
     * @return the value of dm_merchant.LICENSES_NO
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getLicensesNo() {
        return licensesNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.LICENSES_NO
     *
     * @param licensesNo the value for dm_merchant.LICENSES_NO
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setLicensesNo(String licensesNo) {
        this.licensesNo = licensesNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.TAX_NO
     *
     * @return the value of dm_merchant.TAX_NO
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getTaxNo() {
        return taxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.TAX_NO
     *
     * @param taxNo the value for dm_merchant.TAX_NO
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setTaxNo(String taxNo) {
        this.taxNo = taxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.REGISTER_DATE
     *
     * @return the value of dm_merchant.REGISTER_DATE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.REGISTER_DATE
     *
     * @param registerDate the value for dm_merchant.REGISTER_DATE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.STATE
     *
     * @return the value of dm_merchant.STATE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.STATE
     *
     * @param state the value for dm_merchant.STATE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.CREATE_DATE
     *
     * @return the value of dm_merchant.CREATE_DATE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.CREATE_DATE
     *
     * @param createDate the value for dm_merchant.CREATE_DATE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.STATE_DATE
     *
     * @return the value of dm_merchant.STATE_DATE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.STATE_DATE
     *
     * @param stateDate the value for dm_merchant.STATE_DATE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_merchant.MERCHANT_TYPE
     *
     * @return the value of dm_merchant.MERCHANT_TYPE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public String getMerchantType() {
        return merchantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_merchant.MERCHANT_TYPE
     *
     * @param merchantType the value for dm_merchant.MERCHANT_TYPE
     *
     * @mbggenerated Mon Dec 09 09:37:24 CST 2013
     */
    public void setMerchantType(String merchantType) {
        this.merchantType = merchantType;
    }
}