package com.qimeng.bs.system.staticdata.dao;

import com.qimeng.bs.system.staticdata.bean.DcAttrValue;
import org.springframework.stereotype.Repository;

@Repository
public interface DcAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_attr_value
     *
     * @mbggenerated Fri Nov 29 17:29:36 CST 2013
     */
    int deleteByPrimaryKey(Integer attrValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_attr_value
     *
     * @mbggenerated Fri Nov 29 17:29:36 CST 2013
     */
    int insert(DcAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_attr_value
     *
     * @mbggenerated Fri Nov 29 17:29:36 CST 2013
     */
    int insertSelective(DcAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_attr_value
     *
     * @mbggenerated Fri Nov 29 17:29:36 CST 2013
     */
    DcAttrValue selectByPrimaryKey(Integer attrValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_attr_value
     *
     * @mbggenerated Fri Nov 29 17:29:36 CST 2013
     */
    int updateByPrimaryKeySelective(DcAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_attr_value
     *
     * @mbggenerated Fri Nov 29 17:29:36 CST 2013
     */
    int updateByPrimaryKey(DcAttrValue record);
}