package com.qimeng.bs.admin.pay.dao;

import java.util.List;

import com.qimeng.bs.admin.pay.bean.DmPayConfig;

import org.springframework.stereotype.Repository;

@Repository
public interface DmPayConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_pay_config
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    int insert(DmPayConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_pay_config
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    int insertSelective(DmPayConfig record);
    
    List<DmPayConfig> selectAll();
}