package com.qimeng.bs.market.order.bean;

import org.directwebremoting.annotations.DataTransferObject;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

@DataTransferObject
public class DmCustOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.ORDER_ID
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.ORDER_NO
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.MERCHANT_ID
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.AMOUNT
     *
     * @mbggenerated Mon Dec 23 10:07:48 CST 2013
     */
    private Float amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.RELA_MAN
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String relaMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.RELA_TEL
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String relaTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.RELA_PROVINCE
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String relaProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.RELA_CITY
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String relaCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.RELA_DISTRICT
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String relaDistrict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.RELA_ADDR
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String relaAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.ZIP_CODE
     *
     * @mbggenerated Sun Feb 16 16:30:54 CST 2014
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.CARD_TYPE
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.CARD_NO
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.PAYMENT_TYPE
     *
     * @mbggenerated Wed Dec 18 16:14:07 CST 2013
     */
    private String paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.INVOICE_TYPE
     *
     * @mbggenerated Wed Dec 18 16:14:07 CST 2013
     */
    private String invoiceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.INVOICE_NOTES
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String invoiceNotes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.INVOICE_DETAIL
     *
     * @mbggenerated Wed Dec 18 16:14:07 CST 2013
     */
    private String invoiceDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.ORD_NOTES
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String ordNotes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.CREATE_TIME
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.STATE
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.OPER_DATE
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private Date operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.OPER_STAFF_NO
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String operStaffNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_cust_order.OPER_NOTES
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    private String operNotes;
    private float freight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.ORDER_ID
     *
     * @return the value of dm_cust_order.ORDER_ID
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.ORDER_ID
     *
     * @param orderId the value for dm_cust_order.ORDER_ID
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.ORDER_NO
     *
     * @return the value of dm_cust_order.ORDER_NO
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.ORDER_NO
     *
     * @param orderNo the value for dm_cust_order.ORDER_NO
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.MERCHANT_ID
     *
     * @return the value of dm_cust_order.MERCHANT_ID
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.MERCHANT_ID
     *
     * @param merchantId the value for dm_cust_order.MERCHANT_ID
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.AMOUNT
     *
     * @return the value of dm_cust_order.AMOUNT
     *
     * @mbggenerated Mon Dec 23 10:07:48 CST 2013
     */
    public Float getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.AMOUNT
     *
     * @param amount the value for dm_cust_order.AMOUNT
     *
     * @mbggenerated Mon Dec 23 10:07:48 CST 2013
     */
    public void setAmount(Float amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.RELA_MAN
     *
     * @return the value of dm_cust_order.RELA_MAN
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getRelaMan() {
        return relaMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.RELA_MAN
     *
     * @param relaMan the value for dm_cust_order.RELA_MAN
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setRelaMan(String relaMan) {
        this.relaMan = relaMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.RELA_TEL
     *
     * @return the value of dm_cust_order.RELA_TEL
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getRelaTel() {
        return relaTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.RELA_TEL
     *
     * @param relaTel the value for dm_cust_order.RELA_TEL
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setRelaTel(String relaTel) {
        this.relaTel = relaTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.RELA_PROVINCE
     *
     * @return the value of dm_cust_order.RELA_PROVINCE
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getRelaProvince() {
        return relaProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.RELA_PROVINCE
     *
     * @param relaProvince the value for dm_cust_order.RELA_PROVINCE
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setRelaProvince(String relaProvince) {
        this.relaProvince = relaProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.RELA_CITY
     *
     * @return the value of dm_cust_order.RELA_CITY
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getRelaCity() {
        return relaCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.RELA_CITY
     *
     * @param relaCity the value for dm_cust_order.RELA_CITY
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setRelaCity(String relaCity) {
        this.relaCity = relaCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.RELA_DISTRICT
     *
     * @return the value of dm_cust_order.RELA_DISTRICT
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getRelaDistrict() {
        return relaDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.RELA_DISTRICT
     *
     * @param relaDistrict the value for dm_cust_order.RELA_DISTRICT
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setRelaDistrict(String relaDistrict) {
        this.relaDistrict = relaDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.RELA_ADDR
     *
     * @return the value of dm_cust_order.RELA_ADDR
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getRelaAddr() {
        return relaAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.RELA_ADDR
     *
     * @param relaAddr the value for dm_cust_order.RELA_ADDR
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setRelaAddr(String relaAddr) {
        this.relaAddr = relaAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.ZIP_CODE
     *
     * @return the value of dm_cust_order.ZIP_CODE
     *
     * @mbggenerated Sun Feb 16 16:30:54 CST 2014
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.ZIP_CODE
     *
     * @param zipCode the value for dm_cust_order.ZIP_CODE
     *
     * @mbggenerated Sun Feb 16 16:30:54 CST 2014
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.CARD_TYPE
     *
     * @return the value of dm_cust_order.CARD_TYPE
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.CARD_TYPE
     *
     * @param cardType the value for dm_cust_order.CARD_TYPE
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.CARD_NO
     *
     * @return the value of dm_cust_order.CARD_NO
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.CARD_NO
     *
     * @param cardNo the value for dm_cust_order.CARD_NO
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.PAYMENT_TYPE
     *
     * @return the value of dm_cust_order.PAYMENT_TYPE
     *
     * @mbggenerated Wed Dec 18 16:14:07 CST 2013
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.PAYMENT_TYPE
     *
     * @param paymentType the value for dm_cust_order.PAYMENT_TYPE
     *
     * @mbggenerated Wed Dec 18 16:14:07 CST 2013
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.INVOICE_TYPE
     *
     * @return the value of dm_cust_order.INVOICE_TYPE
     *
     * @mbggenerated Wed Dec 18 16:14:07 CST 2013
     */
    public String getInvoiceType() {
        return invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.INVOICE_TYPE
     *
     * @param invoiceType the value for dm_cust_order.INVOICE_TYPE
     *
     * @mbggenerated Wed Dec 18 16:14:07 CST 2013
     */
    public void setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.INVOICE_NOTES
     *
     * @return the value of dm_cust_order.INVOICE_NOTES
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getInvoiceNotes() {
        return invoiceNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.INVOICE_NOTES
     *
     * @param invoiceNotes the value for dm_cust_order.INVOICE_NOTES
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setInvoiceNotes(String invoiceNotes) {
        this.invoiceNotes = invoiceNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.INVOICE_DETAIL
     *
     * @return the value of dm_cust_order.INVOICE_DETAIL
     *
     * @mbggenerated Wed Dec 18 16:14:07 CST 2013
     */
    public String getInvoiceDetail() {
        return invoiceDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.INVOICE_DETAIL
     *
     * @param invoiceDetail the value for dm_cust_order.INVOICE_DETAIL
     *
     * @mbggenerated Wed Dec 18 16:14:07 CST 2013
     */
    public void setInvoiceDetail(String invoiceDetail) {
        this.invoiceDetail = invoiceDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.ORD_NOTES
     *
     * @return the value of dm_cust_order.ORD_NOTES
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getOrdNotes() {
        return ordNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.ORD_NOTES
     *
     * @param ordNotes the value for dm_cust_order.ORD_NOTES
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setOrdNotes(String ordNotes) {
        this.ordNotes = ordNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.CREATE_TIME
     *
     * @return the value of dm_cust_order.CREATE_TIME
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.CREATE_TIME
     *
     * @param createTime the value for dm_cust_order.CREATE_TIME
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.STATE
     *
     * @return the value of dm_cust_order.STATE
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.STATE
     *
     * @param state the value for dm_cust_order.STATE
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.OPER_DATE
     *
     * @return the value of dm_cust_order.OPER_DATE
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public Date getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.OPER_DATE
     *
     * @param operDate the value for dm_cust_order.OPER_DATE
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setOperDate(Date operDate) {
        this.operDate = operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.OPER_STAFF_NO
     *
     * @return the value of dm_cust_order.OPER_STAFF_NO
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getOperStaffNo() {
        return operStaffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.OPER_STAFF_NO
     *
     * @param operStaffNo the value for dm_cust_order.OPER_STAFF_NO
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setOperStaffNo(String operStaffNo) {
        this.operStaffNo = operStaffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_cust_order.OPER_NOTES
     *
     * @return the value of dm_cust_order.OPER_NOTES
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public String getOperNotes() {
        return operNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_cust_order.OPER_NOTES
     *
     * @param operNotes the value for dm_cust_order.OPER_NOTES
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    public void setOperNotes(String operNotes) {
        this.operNotes = operNotes;
    }

    private List<DmSubCustOrder> subCustOrderList = new ArrayList<DmSubCustOrder>();

    public List<DmSubCustOrder> getSubCustOrderList() {
        return subCustOrderList;
    }

    public void setSubCustOrderList(List<DmSubCustOrder> subCustOrderList) {
        this.subCustOrderList = subCustOrderList;
    }

    private int itemNo;

    public int getItemNo() {
        return itemNo;
    }

    public void setItemNo(int itemNo) {
        this.itemNo = itemNo;
    }

    private String fullAddress;

    public String getFullAddress() {
        return this.getRelaProvince()+this.getRelaCity()+this.getRelaDistrict()+this.getRelaAddr();
    }

    public void setFreight(float freight) {
        this.freight = freight;
    }

    public float getFreight() {
        return freight;
    }
}