package com.qimeng.bs.market.order.bean;

import org.directwebremoting.annotations.DataTransferObject;

import java.math.BigDecimal;
import java.util.Date;

@DataTransferObject
public class DmTradeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_trade_log.TRADE_ID
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    private Integer tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_trade_log.ORDER_NO
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_trade_log.INTERFACE_TYPE
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    private String interfaceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_trade_log.AMOUNT
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_trade_log.SEND_CONTENT
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    private String sendContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_trade_log.ACCEPT_CONTENT
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    private String acceptContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_trade_log.TRADE_RESULT
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    private String tradeResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_trade_log.START_TIME
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_trade_log.END_TIME
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_trade_log.TRADE_ID
     *
     * @return the value of dm_trade_log.TRADE_ID
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_trade_log.TRADE_ID
     *
     * @param tradeId the value for dm_trade_log.TRADE_ID
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_trade_log.ORDER_NO
     *
     * @return the value of dm_trade_log.ORDER_NO
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_trade_log.ORDER_NO
     *
     * @param orderNo the value for dm_trade_log.ORDER_NO
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_trade_log.INTERFACE_TYPE
     *
     * @return the value of dm_trade_log.INTERFACE_TYPE
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    public String getInterfaceType() {
        return interfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_trade_log.INTERFACE_TYPE
     *
     * @param interfaceType the value for dm_trade_log.INTERFACE_TYPE
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    public void setInterfaceType(String interfaceType) {
        this.interfaceType = interfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_trade_log.AMOUNT
     *
     * @return the value of dm_trade_log.AMOUNT
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_trade_log.AMOUNT
     *
     * @param amount the value for dm_trade_log.AMOUNT
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_trade_log.SEND_CONTENT
     *
     * @return the value of dm_trade_log.SEND_CONTENT
     *
     * @mbggenerated Wed Mar 05 22:18:37 CST 2014
     */
    public String getSendContent() {
        return sendContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_trade_log.SEND_CONTENT
     *
     * @param sendContent the value for dm_trade_log.SEND_CONTENT
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    public void setSendContent(String sendContent) {
        this.sendContent = sendContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_trade_log.ACCEPT_CONTENT
     *
     * @return the value of dm_trade_log.ACCEPT_CONTENT
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    public String getAcceptContent() {
        return acceptContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_trade_log.ACCEPT_CONTENT
     *
     * @param acceptContent the value for dm_trade_log.ACCEPT_CONTENT
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    public void setAcceptContent(String acceptContent) {
        this.acceptContent = acceptContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_trade_log.TRADE_RESULT
     *
     * @return the value of dm_trade_log.TRADE_RESULT
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    public String getTradeResult() {
        return tradeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_trade_log.TRADE_RESULT
     *
     * @param tradeResult the value for dm_trade_log.TRADE_RESULT
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    public void setTradeResult(String tradeResult) {
        this.tradeResult = tradeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_trade_log.START_TIME
     *
     * @return the value of dm_trade_log.START_TIME
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_trade_log.START_TIME
     *
     * @param startTime the value for dm_trade_log.START_TIME
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_trade_log.END_TIME
     *
     * @return the value of dm_trade_log.END_TIME
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_trade_log.END_TIME
     *
     * @param endTime the value for dm_trade_log.END_TIME
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}