package com.qimeng.bs.market.point.bean;

import org.directwebremoting.annotations.DataTransferObject;

import java.util.Date;

@DataTransferObject
public class DmPoints {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_points.POINT_ID
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    private Integer pointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_points.MERCHANT_ID
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_points.POINT
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_points.ORDER_ID
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    private Integer orderId;
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_points.POINT_DESC
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    private String pointDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_points.GAIN_TIME
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    private Date gainTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_points.EFF_TIME
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    private Date effTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_points.EXP_TIME
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    private Date expTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_points.STATE
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    private String state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_points.POINT_ID
     *
     * @return the value of dm_points.POINT_ID
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public Integer getPointId() {
        return pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_points.POINT_ID
     *
     * @param pointId the value for dm_points.POINT_ID
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public void setPointId(Integer pointId) {
        this.pointId = pointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_points.MERCHANT_ID
     *
     * @return the value of dm_points.MERCHANT_ID
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_points.MERCHANT_ID
     *
     * @param merchantId the value for dm_points.MERCHANT_ID
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_points.POINT
     *
     * @return the value of dm_points.POINT
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_points.POINT
     *
     * @param point the value for dm_points.POINT
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_points.ORDER_ID
     *
     * @return the value of dm_points.ORDER_ID
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_points.ORDER_ID
     *
     * @param orderId the value for dm_points.ORDER_ID
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_points.POINT_DESC
     *
     * @return the value of dm_points.POINT_DESC
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public String getPointDesc() {
        return pointDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_points.POINT_DESC
     *
     * @param pointDesc the value for dm_points.POINT_DESC
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public void setPointDesc(String pointDesc) {
        this.pointDesc = pointDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_points.GAIN_TIME
     *
     * @return the value of dm_points.GAIN_TIME
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public Date getGainTime() {
        return gainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_points.GAIN_TIME
     *
     * @param gainTime the value for dm_points.GAIN_TIME
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public void setGainTime(Date gainTime) {
        this.gainTime = gainTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_points.EFF_TIME
     *
     * @return the value of dm_points.EFF_TIME
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public Date getEffTime() {
        return effTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_points.EFF_TIME
     *
     * @param effTime the value for dm_points.EFF_TIME
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public void setEffTime(Date effTime) {
        this.effTime = effTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_points.EXP_TIME
     *
     * @return the value of dm_points.EXP_TIME
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public Date getExpTime() {
        return expTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_points.EXP_TIME
     *
     * @param expTime the value for dm_points.EXP_TIME
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public void setExpTime(Date expTime) {
        this.expTime = expTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_points.STATE
     *
     * @return the value of dm_points.STATE
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_points.STATE
     *
     * @param state the value for dm_points.STATE
     *
     * @mbggenerated Mon Jan 13 15:47:32 CST 2014
     */
    public void setState(String state) {
        this.state = state;
    }

    public String getOrderNo() {
      return orderNo;
    }

    public void setOrderNo(String orderNo) {
      this.orderNo = orderNo;
    }
}