package com.qimeng.bs.admin.pay.bean;

public class DmPayConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_pay_config.ID
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_pay_config.PARAM_CODE
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    private String paramCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_pay_config.PARAM_VALUE
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    private String paramValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_pay_config.PARAM_DESC
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    private String paramDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_pay_config.ID
     *
     * @return the value of dm_pay_config.ID
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_pay_config.ID
     *
     * @param id the value for dm_pay_config.ID
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_pay_config.PARAM_CODE
     *
     * @return the value of dm_pay_config.PARAM_CODE
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    public String getParamCode() {
        return paramCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_pay_config.PARAM_CODE
     *
     * @param paramCode the value for dm_pay_config.PARAM_CODE
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    public void setParamCode(String paramCode) {
        this.paramCode = paramCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_pay_config.PARAM_VALUE
     *
     * @return the value of dm_pay_config.PARAM_VALUE
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_pay_config.PARAM_VALUE
     *
     * @param paramValue the value for dm_pay_config.PARAM_VALUE
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_pay_config.PARAM_DESC
     *
     * @return the value of dm_pay_config.PARAM_DESC
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    public String getParamDesc() {
        return paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_pay_config.PARAM_DESC
     *
     * @param paramDesc the value for dm_pay_config.PARAM_DESC
     *
     * @mbggenerated Fri Dec 20 15:46:30 CST 2013
     */
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc;
    }
}