package com.qimeng.bs.market.order.dao;

import com.qimeng.bs.market.order.bean.DmOrderInvoice;
import com.qimeng.common.Page;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DmOrderInvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_order_invoice
     *
     * @mbggenerated Fri Jan 03 16:34:03 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_order_invoice
     *
     * @mbggenerated Fri Jan 03 16:34:03 CST 2014
     */
    int insert(DmOrderInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_order_invoice
     *
     * @mbggenerated Fri Jan 03 16:34:03 CST 2014
     */
    int insertSelective(DmOrderInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_order_invoice
     *
     * @mbggenerated Fri Jan 03 16:34:03 CST 2014
     */
    DmOrderInvoice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_order_invoice
     *
     * @mbggenerated Fri Jan 03 16:34:03 CST 2014
     */
    int updateByPrimaryKeySelective(DmOrderInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_order_invoice
     *
     * @mbggenerated Fri Jan 03 16:34:03 CST 2014
     */
    int updateByPrimaryKey(DmOrderInvoice record);
    
    List<DmOrderInvoice> selectOrderInvoiceByPage(Page page);
}