package com.qimeng.bs.market.order.dao;

import com.qimeng.common.Page;
import com.qimeng.bs.market.order.bean.DmSubCustOrder;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Repository
public interface DmSubCustOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_sub_cust_order
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    int deleteByPrimaryKey(Integer subOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_sub_cust_order
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    int insert(DmSubCustOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_sub_cust_order
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    int insertSelective(DmSubCustOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_sub_cust_order
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    DmSubCustOrder selectByPrimaryKey(Integer subOrderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_sub_cust_order
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    int updateByPrimaryKeySelective(DmSubCustOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_sub_cust_order
     *
     * @mbggenerated Mon Dec 09 09:41:23 CST 2013
     */
    int updateByPrimaryKey(DmSubCustOrder record);

    List<DmSubCustOrder> selectSubOrderByOrderId(Integer orderId);

    int updateOrderState(Map params);

    List<DmSubCustOrder> selectSubOrderByOrderIdPage(Page page);

    DmSubCustOrder selectCommentOrder(Map params);


    void deleteSubOrderByOrderId(Integer orderId);
}