package com.qimeng.bs.market.order.dao;

import com.qimeng.bs.market.order.bean.DmTradeLog;
import org.springframework.stereotype.Repository;

@Repository
public interface DmTradeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_trade_log
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    int deleteByPrimaryKey(Integer tradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_trade_log
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    int insert(DmTradeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_trade_log
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    int insertSelective(DmTradeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_trade_log
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    DmTradeLog selectByPrimaryKey(Integer tradeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_trade_log
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    int updateByPrimaryKeySelective(DmTradeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_trade_log
     *
     * @mbggenerated Fri Jan 03 14:27:27 CST 2014
     */
    int updateByPrimaryKey(DmTradeLog record);
    
    DmTradeLog selectTradeLogByOrderId(Integer orderId);
}