package com.qimeng.bs.admin.security.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.qimeng.bs.admin.security.bean.DmOrganization;
@Repository
public interface DmOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_organization
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    int deleteByPrimaryKey(Integer orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_organization
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    int insert(DmOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_organization
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    int insertSelective(DmOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_organization
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    DmOrganization selectByPrimaryKey(Integer orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_organization
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    int updateByPrimaryKeySelective(DmOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_organization
     *
     * @mbggenerated Tue Dec 03 10:02:11 CST 2013
     */
    int updateByPrimaryKey(DmOrganization record);
    
    List<DmOrganization> findOrgs(Object params);
}